/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package app.marquee.api.apis

import java.io.IOException
import okhttp3.Call
import okhttp3.HttpUrl

import app.marquee.api.models.Error
import app.marquee.api.models.HealthCheck
import app.marquee.api.models.HealthIssuePage
import app.marquee.api.models.Library
import app.marquee.api.models.LibraryCreate
import app.marquee.api.models.LibraryUpdate

import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

import app.marquee.api.infrastructure.ApiClient
import app.marquee.api.infrastructure.ApiResponse
import app.marquee.api.infrastructure.ClientException
import app.marquee.api.infrastructure.ClientError
import app.marquee.api.infrastructure.ServerException
import app.marquee.api.infrastructure.ServerError
import app.marquee.api.infrastructure.MultiValueMap
import app.marquee.api.infrastructure.PartConfig
import app.marquee.api.infrastructure.RequestConfig
import app.marquee.api.infrastructure.RequestMethod
import app.marquee.api.infrastructure.ResponseType
import app.marquee.api.infrastructure.Success
import app.marquee.api.infrastructure.toMultiValue
import app.marquee.api.infrastructure.Serializer

open class LibrariesApi(basePath: kotlin.String = defaultBasePath, client: Call.Factory = ApiClient.defaultClient) : ApiClient(basePath, client) {
    companion object {
        @JvmStatic
        val defaultBasePath: String by lazy {
            System.getProperties().getProperty(ApiClient.BASE_URL_KEY, "/api/v1")
        }
    }

    /**
     * DELETE /libraries/{libraryId}/scan
     * Cancel a queued or running scan (admin only).
     * 
     * @param libraryId 
     * @return void
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    fun cancelLibraryScan(libraryId: kotlin.Long) : Unit {
        val localVarResponse = cancelLibraryScanWithHttpInfo(libraryId = libraryId)

        return when (localVarResponse.responseType) {
            ResponseType.Success -> Unit
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
     * DELETE /libraries/{libraryId}/scan
     * Cancel a queued or running scan (admin only).
     * 
     * @param libraryId 
     * @return ApiResponse<Unit?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Throws(IllegalStateException::class, IOException::class)
    fun cancelLibraryScanWithHttpInfo(libraryId: kotlin.Long) : ApiResponse<Unit?> {
        val localVariableConfig = cancelLibraryScanRequestConfig(libraryId = libraryId)

        return request<Unit, Unit>(
            localVariableConfig
        )
    }

    /**
     * To obtain the request config of the operation cancelLibraryScan
     *
     * @param libraryId 
     * @return RequestConfig
     */
    fun cancelLibraryScanRequestConfig(libraryId: kotlin.Long) : RequestConfig<Unit> {
        val localVariableBody = null
        val localVariableQuery: MultiValueMap = mutableMapOf()
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        localVariableHeaders["Accept"] = "application/json"

        return RequestConfig(
            method = RequestMethod.DELETE,
            path = "/libraries/{libraryId}/scan".replace("{"+"libraryId"+"}", encodeURIComponent(libraryId.toString())),
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
            body = localVariableBody
        )
    }

    /**
     * POST /libraries
     * Create a library (admin only).
     * 
     * @param libraryCreate 
     * @return Library
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    fun createLibrary(libraryCreate: LibraryCreate) : Library {
        val localVarResponse = createLibraryWithHttpInfo(libraryCreate = libraryCreate)

        return when (localVarResponse.responseType) {
            ResponseType.Success -> (localVarResponse as Success<*>).data as Library
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
     * POST /libraries
     * Create a library (admin only).
     * 
     * @param libraryCreate 
     * @return ApiResponse<Library?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class)
    fun createLibraryWithHttpInfo(libraryCreate: LibraryCreate) : ApiResponse<Library?> {
        val localVariableConfig = createLibraryRequestConfig(libraryCreate = libraryCreate)

        return request<LibraryCreate, Library>(
            localVariableConfig
        )
    }

    /**
     * To obtain the request config of the operation createLibrary
     *
     * @param libraryCreate 
     * @return RequestConfig
     */
    fun createLibraryRequestConfig(libraryCreate: LibraryCreate) : RequestConfig<LibraryCreate> {
        val localVariableBody = libraryCreate
        val localVariableQuery: MultiValueMap = mutableMapOf()
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        localVariableHeaders["Content-Type"] = "application/json"
        localVariableHeaders["Accept"] = "application/json"

        return RequestConfig(
            method = RequestMethod.POST,
            path = "/libraries",
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
            body = localVariableBody
        )
    }

    /**
     * DELETE /libraries/{libraryId}
     * Delete a library and its metadata (admin only). Media files are never touched.
     * 
     * @param libraryId 
     * @return void
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    fun deleteLibrary(libraryId: kotlin.Long) : Unit {
        val localVarResponse = deleteLibraryWithHttpInfo(libraryId = libraryId)

        return when (localVarResponse.responseType) {
            ResponseType.Success -> Unit
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
     * DELETE /libraries/{libraryId}
     * Delete a library and its metadata (admin only). Media files are never touched.
     * 
     * @param libraryId 
     * @return ApiResponse<Unit?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Throws(IllegalStateException::class, IOException::class)
    fun deleteLibraryWithHttpInfo(libraryId: kotlin.Long) : ApiResponse<Unit?> {
        val localVariableConfig = deleteLibraryRequestConfig(libraryId = libraryId)

        return request<Unit, Unit>(
            localVariableConfig
        )
    }

    /**
     * To obtain the request config of the operation deleteLibrary
     *
     * @param libraryId 
     * @return RequestConfig
     */
    fun deleteLibraryRequestConfig(libraryId: kotlin.Long) : RequestConfig<Unit> {
        val localVariableBody = null
        val localVariableQuery: MultiValueMap = mutableMapOf()
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        localVariableHeaders["Accept"] = "application/json"

        return RequestConfig(
            method = RequestMethod.DELETE,
            path = "/libraries/{libraryId}".replace("{"+"libraryId"+"}", encodeURIComponent(libraryId.toString())),
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
            body = localVariableBody
        )
    }

    /**
     * DELETE /files/{fileId}
     * Delete a media file from Library Health (ADM-11, admin only, when allowMediaDeletion is on).
     * The file, and the subtitles and artwork beside it that belong only to it, move to a .marquee-trash folder in its library folder and are removed for good after 30 days. When it was the item&#39;s last file the item goes too, along with a season or show left empty.
     * @param fileId 
     * @return void
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    fun deleteMediaFile(fileId: kotlin.Long) : Unit {
        val localVarResponse = deleteMediaFileWithHttpInfo(fileId = fileId)

        return when (localVarResponse.responseType) {
            ResponseType.Success -> Unit
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
     * DELETE /files/{fileId}
     * Delete a media file from Library Health (ADM-11, admin only, when allowMediaDeletion is on).
     * The file, and the subtitles and artwork beside it that belong only to it, move to a .marquee-trash folder in its library folder and are removed for good after 30 days. When it was the item&#39;s last file the item goes too, along with a season or show left empty.
     * @param fileId 
     * @return ApiResponse<Unit?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Throws(IllegalStateException::class, IOException::class)
    fun deleteMediaFileWithHttpInfo(fileId: kotlin.Long) : ApiResponse<Unit?> {
        val localVariableConfig = deleteMediaFileRequestConfig(fileId = fileId)

        return request<Unit, Unit>(
            localVariableConfig
        )
    }

    /**
     * To obtain the request config of the operation deleteMediaFile
     *
     * @param fileId 
     * @return RequestConfig
     */
    fun deleteMediaFileRequestConfig(fileId: kotlin.Long) : RequestConfig<Unit> {
        val localVariableBody = null
        val localVariableQuery: MultiValueMap = mutableMapOf()
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        localVariableHeaders["Accept"] = "application/json"

        return RequestConfig(
            method = RequestMethod.DELETE,
            path = "/files/{fileId}".replace("{"+"fileId"+"}", encodeURIComponent(fileId.toString())),
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
            body = localVariableBody
        )
    }

    /**
     * GET /libraries/{libraryId}
     * 
     * 
     * @param libraryId 
     * @return Library
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    fun getLibrary(libraryId: kotlin.Long) : Library {
        val localVarResponse = getLibraryWithHttpInfo(libraryId = libraryId)

        return when (localVarResponse.responseType) {
            ResponseType.Success -> (localVarResponse as Success<*>).data as Library
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
     * GET /libraries/{libraryId}
     * 
     * 
     * @param libraryId 
     * @return ApiResponse<Library?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class)
    fun getLibraryWithHttpInfo(libraryId: kotlin.Long) : ApiResponse<Library?> {
        val localVariableConfig = getLibraryRequestConfig(libraryId = libraryId)

        return request<Unit, Library>(
            localVariableConfig
        )
    }

    /**
     * To obtain the request config of the operation getLibrary
     *
     * @param libraryId 
     * @return RequestConfig
     */
    fun getLibraryRequestConfig(libraryId: kotlin.Long) : RequestConfig<Unit> {
        val localVariableBody = null
        val localVariableQuery: MultiValueMap = mutableMapOf()
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        localVariableHeaders["Accept"] = "application/json"

        return RequestConfig(
            method = RequestMethod.GET,
            path = "/libraries/{libraryId}".replace("{"+"libraryId"+"}", encodeURIComponent(libraryId.toString())),
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
            body = localVariableBody
        )
    }

    /**
     * PUT /library-health/{checkId}/ignored/{itemId}
     * Stop reporting this item for this check (admin only).
     * 
     * @param checkId 
     * @param itemId 
     * @return void
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    fun ignoreHealthIssue(checkId: kotlin.String, itemId: kotlin.Long) : Unit {
        val localVarResponse = ignoreHealthIssueWithHttpInfo(checkId = checkId, itemId = itemId)

        return when (localVarResponse.responseType) {
            ResponseType.Success -> Unit
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
     * PUT /library-health/{checkId}/ignored/{itemId}
     * Stop reporting this item for this check (admin only).
     * 
     * @param checkId 
     * @param itemId 
     * @return ApiResponse<Unit?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Throws(IllegalStateException::class, IOException::class)
    fun ignoreHealthIssueWithHttpInfo(checkId: kotlin.String, itemId: kotlin.Long) : ApiResponse<Unit?> {
        val localVariableConfig = ignoreHealthIssueRequestConfig(checkId = checkId, itemId = itemId)

        return request<Unit, Unit>(
            localVariableConfig
        )
    }

    /**
     * To obtain the request config of the operation ignoreHealthIssue
     *
     * @param checkId 
     * @param itemId 
     * @return RequestConfig
     */
    fun ignoreHealthIssueRequestConfig(checkId: kotlin.String, itemId: kotlin.Long) : RequestConfig<Unit> {
        val localVariableBody = null
        val localVariableQuery: MultiValueMap = mutableMapOf()
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        localVariableHeaders["Accept"] = "application/json"

        return RequestConfig(
            method = RequestMethod.PUT,
            path = "/library-health/{checkId}/ignored/{itemId}".replace("{"+"checkId"+"}", encodeURIComponent(checkId.toString())).replace("{"+"itemId"+"}", encodeURIComponent(itemId.toString())),
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
            body = localVariableBody
        )
    }

    /**
     * GET /library-health
     * Library health checks with how many items each found (ADM-11, admin only).
     * 
     * @return kotlin.collections.List<HealthCheck>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    fun libraryHealth() : kotlin.collections.List<HealthCheck> {
        val localVarResponse = libraryHealthWithHttpInfo()

        return when (localVarResponse.responseType) {
            ResponseType.Success -> (localVarResponse as Success<*>).data as kotlin.collections.List<HealthCheck>
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
     * GET /library-health
     * Library health checks with how many items each found (ADM-11, admin only).
     * 
     * @return ApiResponse<kotlin.collections.List<HealthCheck>?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class)
    fun libraryHealthWithHttpInfo() : ApiResponse<kotlin.collections.List<HealthCheck>?> {
        val localVariableConfig = libraryHealthRequestConfig()

        return request<Unit, kotlin.collections.List<HealthCheck>>(
            localVariableConfig
        )
    }

    /**
     * To obtain the request config of the operation libraryHealth
     *
     * @return RequestConfig
     */
    fun libraryHealthRequestConfig() : RequestConfig<Unit> {
        val localVariableBody = null
        val localVariableQuery: MultiValueMap = mutableMapOf()
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        localVariableHeaders["Accept"] = "application/json"

        return RequestConfig(
            method = RequestMethod.GET,
            path = "/library-health",
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
            body = localVariableBody
        )
    }

    /**
     * GET /library-health/{checkId}
     * What one check found (admin only). Ignored items are left out.
     * 
     * @param checkId 
     * @param offset  (optional, default to 0)
     * @param limit  (optional, default to 100)
     * @return HealthIssuePage
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    fun libraryHealthIssues(checkId: kotlin.String, offset: kotlin.Int? = 0, limit: kotlin.Int? = 100) : HealthIssuePage {
        val localVarResponse = libraryHealthIssuesWithHttpInfo(checkId = checkId, offset = offset, limit = limit)

        return when (localVarResponse.responseType) {
            ResponseType.Success -> (localVarResponse as Success<*>).data as HealthIssuePage
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
     * GET /library-health/{checkId}
     * What one check found (admin only). Ignored items are left out.
     * 
     * @param checkId 
     * @param offset  (optional, default to 0)
     * @param limit  (optional, default to 100)
     * @return ApiResponse<HealthIssuePage?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class)
    fun libraryHealthIssuesWithHttpInfo(checkId: kotlin.String, offset: kotlin.Int?, limit: kotlin.Int?) : ApiResponse<HealthIssuePage?> {
        val localVariableConfig = libraryHealthIssuesRequestConfig(checkId = checkId, offset = offset, limit = limit)

        return request<Unit, HealthIssuePage>(
            localVariableConfig
        )
    }

    /**
     * To obtain the request config of the operation libraryHealthIssues
     *
     * @param checkId 
     * @param offset  (optional, default to 0)
     * @param limit  (optional, default to 100)
     * @return RequestConfig
     */
    fun libraryHealthIssuesRequestConfig(checkId: kotlin.String, offset: kotlin.Int?, limit: kotlin.Int?) : RequestConfig<Unit> {
        val localVariableBody = null
        val localVariableQuery: MultiValueMap = mutableMapOf<kotlin.String, kotlin.collections.List<kotlin.String>>()
            .apply {
                if (offset != null) {
                    put("offset", listOf(offset.toString()))
                }
                if (limit != null) {
                    put("limit", listOf(limit.toString()))
                }
            }
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        localVariableHeaders["Accept"] = "application/json"

        return RequestConfig(
            method = RequestMethod.GET,
            path = "/library-health/{checkId}".replace("{"+"checkId"+"}", encodeURIComponent(checkId.toString())),
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
            body = localVariableBody
        )
    }

    /**
     * GET /libraries
     * Libraries visible to the current user.
     * 
     * @return kotlin.collections.List<Library>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    fun listLibraries() : kotlin.collections.List<Library> {
        val localVarResponse = listLibrariesWithHttpInfo()

        return when (localVarResponse.responseType) {
            ResponseType.Success -> (localVarResponse as Success<*>).data as kotlin.collections.List<Library>
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
     * GET /libraries
     * Libraries visible to the current user.
     * 
     * @return ApiResponse<kotlin.collections.List<Library>?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class)
    fun listLibrariesWithHttpInfo() : ApiResponse<kotlin.collections.List<Library>?> {
        val localVariableConfig = listLibrariesRequestConfig()

        return request<Unit, kotlin.collections.List<Library>>(
            localVariableConfig
        )
    }

    /**
     * To obtain the request config of the operation listLibraries
     *
     * @return RequestConfig
     */
    fun listLibrariesRequestConfig() : RequestConfig<Unit> {
        val localVariableBody = null
        val localVariableQuery: MultiValueMap = mutableMapOf()
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        localVariableHeaders["Accept"] = "application/json"

        return RequestConfig(
            method = RequestMethod.GET,
            path = "/libraries",
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
            body = localVariableBody
        )
    }

    /**
     * POST /libraries/scan
     * Queue a scan of every library (admin only).
     * 
     * @return void
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    fun scanAllLibraries() : Unit {
        val localVarResponse = scanAllLibrariesWithHttpInfo()

        return when (localVarResponse.responseType) {
            ResponseType.Success -> Unit
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
     * POST /libraries/scan
     * Queue a scan of every library (admin only).
     * 
     * @return ApiResponse<Unit?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Throws(IllegalStateException::class, IOException::class)
    fun scanAllLibrariesWithHttpInfo() : ApiResponse<Unit?> {
        val localVariableConfig = scanAllLibrariesRequestConfig()

        return request<Unit, Unit>(
            localVariableConfig
        )
    }

    /**
     * To obtain the request config of the operation scanAllLibraries
     *
     * @return RequestConfig
     */
    fun scanAllLibrariesRequestConfig() : RequestConfig<Unit> {
        val localVariableBody = null
        val localVariableQuery: MultiValueMap = mutableMapOf()
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        localVariableHeaders["Accept"] = "application/json"

        return RequestConfig(
            method = RequestMethod.POST,
            path = "/libraries/scan",
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
            body = localVariableBody
        )
    }

    /**
     * POST /libraries/{libraryId}/scan
     * Queue a scan of one library (admin only). Returns immediately; poll the library for progress.
     * 
     * @param libraryId 
     * @return Library
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    fun scanLibrary(libraryId: kotlin.Long) : Library {
        val localVarResponse = scanLibraryWithHttpInfo(libraryId = libraryId)

        return when (localVarResponse.responseType) {
            ResponseType.Success -> (localVarResponse as Success<*>).data as Library
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
     * POST /libraries/{libraryId}/scan
     * Queue a scan of one library (admin only). Returns immediately; poll the library for progress.
     * 
     * @param libraryId 
     * @return ApiResponse<Library?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class)
    fun scanLibraryWithHttpInfo(libraryId: kotlin.Long) : ApiResponse<Library?> {
        val localVariableConfig = scanLibraryRequestConfig(libraryId = libraryId)

        return request<Unit, Library>(
            localVariableConfig
        )
    }

    /**
     * To obtain the request config of the operation scanLibrary
     *
     * @param libraryId 
     * @return RequestConfig
     */
    fun scanLibraryRequestConfig(libraryId: kotlin.Long) : RequestConfig<Unit> {
        val localVariableBody = null
        val localVariableQuery: MultiValueMap = mutableMapOf()
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        localVariableHeaders["Accept"] = "application/json"

        return RequestConfig(
            method = RequestMethod.POST,
            path = "/libraries/{libraryId}/scan".replace("{"+"libraryId"+"}", encodeURIComponent(libraryId.toString())),
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
            body = localVariableBody
        )
    }

    /**
     * DELETE /library-health/{checkId}/ignored/{itemId}
     * Report it again (admin only).
     * 
     * @param checkId 
     * @param itemId 
     * @return void
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    fun unignoreHealthIssue(checkId: kotlin.String, itemId: kotlin.Long) : Unit {
        val localVarResponse = unignoreHealthIssueWithHttpInfo(checkId = checkId, itemId = itemId)

        return when (localVarResponse.responseType) {
            ResponseType.Success -> Unit
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
     * DELETE /library-health/{checkId}/ignored/{itemId}
     * Report it again (admin only).
     * 
     * @param checkId 
     * @param itemId 
     * @return ApiResponse<Unit?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Throws(IllegalStateException::class, IOException::class)
    fun unignoreHealthIssueWithHttpInfo(checkId: kotlin.String, itemId: kotlin.Long) : ApiResponse<Unit?> {
        val localVariableConfig = unignoreHealthIssueRequestConfig(checkId = checkId, itemId = itemId)

        return request<Unit, Unit>(
            localVariableConfig
        )
    }

    /**
     * To obtain the request config of the operation unignoreHealthIssue
     *
     * @param checkId 
     * @param itemId 
     * @return RequestConfig
     */
    fun unignoreHealthIssueRequestConfig(checkId: kotlin.String, itemId: kotlin.Long) : RequestConfig<Unit> {
        val localVariableBody = null
        val localVariableQuery: MultiValueMap = mutableMapOf()
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        localVariableHeaders["Accept"] = "application/json"

        return RequestConfig(
            method = RequestMethod.DELETE,
            path = "/library-health/{checkId}/ignored/{itemId}".replace("{"+"checkId"+"}", encodeURIComponent(checkId.toString())).replace("{"+"itemId"+"}", encodeURIComponent(itemId.toString())),
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
            body = localVariableBody
        )
    }

    /**
     * PATCH /libraries/{libraryId}
     * Update a library (admin only). Type cannot be changed.
     * 
     * @param libraryId 
     * @param libraryUpdate 
     * @return Library
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    fun updateLibrary(libraryId: kotlin.Long, libraryUpdate: LibraryUpdate) : Library {
        val localVarResponse = updateLibraryWithHttpInfo(libraryId = libraryId, libraryUpdate = libraryUpdate)

        return when (localVarResponse.responseType) {
            ResponseType.Success -> (localVarResponse as Success<*>).data as Library
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
     * PATCH /libraries/{libraryId}
     * Update a library (admin only). Type cannot be changed.
     * 
     * @param libraryId 
     * @param libraryUpdate 
     * @return ApiResponse<Library?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class)
    fun updateLibraryWithHttpInfo(libraryId: kotlin.Long, libraryUpdate: LibraryUpdate) : ApiResponse<Library?> {
        val localVariableConfig = updateLibraryRequestConfig(libraryId = libraryId, libraryUpdate = libraryUpdate)

        return request<LibraryUpdate, Library>(
            localVariableConfig
        )
    }

    /**
     * To obtain the request config of the operation updateLibrary
     *
     * @param libraryId 
     * @param libraryUpdate 
     * @return RequestConfig
     */
    fun updateLibraryRequestConfig(libraryId: kotlin.Long, libraryUpdate: LibraryUpdate) : RequestConfig<LibraryUpdate> {
        val localVariableBody = libraryUpdate
        val localVariableQuery: MultiValueMap = mutableMapOf()
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        localVariableHeaders["Content-Type"] = "application/json"
        localVariableHeaders["Accept"] = "application/json"

        return RequestConfig(
            method = RequestMethod.PATCH,
            path = "/libraries/{libraryId}".replace("{"+"libraryId"+"}", encodeURIComponent(libraryId.toString())),
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
            body = localVariableBody
        )
    }


    private fun encodeURIComponent(uriComponent: kotlin.String): kotlin.String =
        HttpUrl.Builder().scheme("http").host("localhost").addPathSegment(uriComponent).build().encodedPathSegments[0]
}
