/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package app.marquee.api.apis

import java.io.IOException
import okhttp3.Call
import okhttp3.HttpUrl

import app.marquee.api.models.Error
import app.marquee.api.models.ListLiveGroups200ResponseInner
import app.marquee.api.models.LiveChannel
import app.marquee.api.models.LiveGuide200ResponseInner
import app.marquee.api.models.LiveSession
import app.marquee.api.models.LiveTvStatus
import app.marquee.api.models.PlayLiveChannelRequest
import app.marquee.api.models.Recording
import app.marquee.api.models.RecordingRule
import app.marquee.api.models.ScheduleRecording201Response
import app.marquee.api.models.ScheduleRecordingRequest

import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

import app.marquee.api.infrastructure.ApiClient
import app.marquee.api.infrastructure.ApiResponse
import app.marquee.api.infrastructure.ClientException
import app.marquee.api.infrastructure.ClientError
import app.marquee.api.infrastructure.ServerException
import app.marquee.api.infrastructure.ServerError
import app.marquee.api.infrastructure.MultiValueMap
import app.marquee.api.infrastructure.PartConfig
import app.marquee.api.infrastructure.RequestConfig
import app.marquee.api.infrastructure.RequestMethod
import app.marquee.api.infrastructure.ResponseType
import app.marquee.api.infrastructure.Success
import app.marquee.api.infrastructure.toMultiValue
import app.marquee.api.infrastructure.Serializer

open class LivetvApi(basePath: kotlin.String = defaultBasePath, client: Call.Factory = ApiClient.defaultClient) : ApiClient(basePath, client) {
    companion object {
        @JvmStatic
        val defaultBasePath: String by lazy {
            System.getProperties().getProperty(ApiClient.BASE_URL_KEY, "/api/v1")
        }
    }

    /**
     * DELETE /livetv/recordings/{recordingId}
     * Cancel an upcoming recording, stop one in progress (keeping what was recorded), or remove a finished one from the list.
     * 
     * @param recordingId 
     * @param deleteFile Finished recordings: delete the file too (admins, or whoever scheduled it). (optional)
     * @return void
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    fun cancelRecording(recordingId: kotlin.Long, deleteFile: kotlin.Boolean? = null) : Unit {
        val localVarResponse = cancelRecordingWithHttpInfo(recordingId = recordingId, deleteFile = deleteFile)

        return when (localVarResponse.responseType) {
            ResponseType.Success -> Unit
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
     * DELETE /livetv/recordings/{recordingId}
     * Cancel an upcoming recording, stop one in progress (keeping what was recorded), or remove a finished one from the list.
     * 
     * @param recordingId 
     * @param deleteFile Finished recordings: delete the file too (admins, or whoever scheduled it). (optional)
     * @return ApiResponse<Unit?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Throws(IllegalStateException::class, IOException::class)
    fun cancelRecordingWithHttpInfo(recordingId: kotlin.Long, deleteFile: kotlin.Boolean?) : ApiResponse<Unit?> {
        val localVariableConfig = cancelRecordingRequestConfig(recordingId = recordingId, deleteFile = deleteFile)

        return request<Unit, Unit>(
            localVariableConfig
        )
    }

    /**
     * To obtain the request config of the operation cancelRecording
     *
     * @param recordingId 
     * @param deleteFile Finished recordings: delete the file too (admins, or whoever scheduled it). (optional)
     * @return RequestConfig
     */
    fun cancelRecordingRequestConfig(recordingId: kotlin.Long, deleteFile: kotlin.Boolean?) : RequestConfig<Unit> {
        val localVariableBody = null
        val localVariableQuery: MultiValueMap = mutableMapOf<kotlin.String, kotlin.collections.List<kotlin.String>>()
            .apply {
                if (deleteFile != null) {
                    put("deleteFile", listOf(deleteFile.toString()))
                }
            }
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        localVariableHeaders["Accept"] = "application/json"

        return RequestConfig(
            method = RequestMethod.DELETE,
            path = "/livetv/recordings/{recordingId}".replace("{"+"recordingId"+"}", encodeURIComponent(recordingId.toString())),
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
            body = localVariableBody
        )
    }

    /**
     * DELETE /livetv/recording-rules/{ruleId}
     * Stop recording a series. Its upcoming airings are dropped; recordings already made stay.
     * 
     * @param ruleId 
     * @return void
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    fun deleteRecordingRule(ruleId: kotlin.Long) : Unit {
        val localVarResponse = deleteRecordingRuleWithHttpInfo(ruleId = ruleId)

        return when (localVarResponse.responseType) {
            ResponseType.Success -> Unit
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
     * DELETE /livetv/recording-rules/{ruleId}
     * Stop recording a series. Its upcoming airings are dropped; recordings already made stay.
     * 
     * @param ruleId 
     * @return ApiResponse<Unit?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Throws(IllegalStateException::class, IOException::class)
    fun deleteRecordingRuleWithHttpInfo(ruleId: kotlin.Long) : ApiResponse<Unit?> {
        val localVariableConfig = deleteRecordingRuleRequestConfig(ruleId = ruleId)

        return request<Unit, Unit>(
            localVariableConfig
        )
    }

    /**
     * To obtain the request config of the operation deleteRecordingRule
     *
     * @param ruleId 
     * @return RequestConfig
     */
    fun deleteRecordingRuleRequestConfig(ruleId: kotlin.Long) : RequestConfig<Unit> {
        val localVariableBody = null
        val localVariableQuery: MultiValueMap = mutableMapOf()
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        localVariableHeaders["Accept"] = "application/json"

        return RequestConfig(
            method = RequestMethod.DELETE,
            path = "/livetv/recording-rules/{ruleId}".replace("{"+"ruleId"+"}", encodeURIComponent(ruleId.toString())),
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
            body = localVariableBody
        )
    }

    /**
     * PUT /livetv/channels/{channelId}/favorite
     * Add a channel to the caller&#39;s favourites.
     * 
     * @param channelId 
     * @return void
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    fun favoriteLiveChannel(channelId: kotlin.Long) : Unit {
        val localVarResponse = favoriteLiveChannelWithHttpInfo(channelId = channelId)

        return when (localVarResponse.responseType) {
            ResponseType.Success -> Unit
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
     * PUT /livetv/channels/{channelId}/favorite
     * Add a channel to the caller&#39;s favourites.
     * 
     * @param channelId 
     * @return ApiResponse<Unit?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Throws(IllegalStateException::class, IOException::class)
    fun favoriteLiveChannelWithHttpInfo(channelId: kotlin.Long) : ApiResponse<Unit?> {
        val localVariableConfig = favoriteLiveChannelRequestConfig(channelId = channelId)

        return request<Unit, Unit>(
            localVariableConfig
        )
    }

    /**
     * To obtain the request config of the operation favoriteLiveChannel
     *
     * @param channelId 
     * @return RequestConfig
     */
    fun favoriteLiveChannelRequestConfig(channelId: kotlin.Long) : RequestConfig<Unit> {
        val localVariableBody = null
        val localVariableQuery: MultiValueMap = mutableMapOf()
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        localVariableHeaders["Accept"] = "application/json"

        return RequestConfig(
            method = RequestMethod.PUT,
            path = "/livetv/channels/{channelId}/favorite".replace("{"+"channelId"+"}", encodeURIComponent(channelId.toString())),
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
            body = localVariableBody
        )
    }

    /**
     * PUT /livetv/channels/{channelId}/hidden
     * Hide a channel from the caller&#39;s guide (LIVE-4).
     * 
     * @param channelId 
     * @return void
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    fun hideLiveChannel(channelId: kotlin.Long) : Unit {
        val localVarResponse = hideLiveChannelWithHttpInfo(channelId = channelId)

        return when (localVarResponse.responseType) {
            ResponseType.Success -> Unit
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
     * PUT /livetv/channels/{channelId}/hidden
     * Hide a channel from the caller&#39;s guide (LIVE-4).
     * 
     * @param channelId 
     * @return ApiResponse<Unit?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Throws(IllegalStateException::class, IOException::class)
    fun hideLiveChannelWithHttpInfo(channelId: kotlin.Long) : ApiResponse<Unit?> {
        val localVariableConfig = hideLiveChannelRequestConfig(channelId = channelId)

        return request<Unit, Unit>(
            localVariableConfig
        )
    }

    /**
     * To obtain the request config of the operation hideLiveChannel
     *
     * @param channelId 
     * @return RequestConfig
     */
    fun hideLiveChannelRequestConfig(channelId: kotlin.Long) : RequestConfig<Unit> {
        val localVariableBody = null
        val localVariableQuery: MultiValueMap = mutableMapOf()
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        localVariableHeaders["Accept"] = "application/json"

        return RequestConfig(
            method = RequestMethod.PUT,
            path = "/livetv/channels/{channelId}/hidden".replace("{"+"channelId"+"}", encodeURIComponent(channelId.toString())),
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
            body = localVariableBody
        )
    }

    /**
     * GET /livetv/channels
     * Channels in number order, with what&#39;s on now and next.
     * 
     * @param group Only this group (category). (optional)
     * @param favorites Only the caller&#39;s favourites. (optional)
     * @param recent The channels the caller watched last, newest first (LIVE-4). (optional)
     * @param hidden Only the channels the caller hid (otherwise they&#39;re left out). (optional)
     * @return kotlin.collections.List<LiveChannel>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    fun listLiveChannels(group: kotlin.String? = null, favorites: kotlin.Boolean? = null, recent: kotlin.Boolean? = null, hidden: kotlin.Boolean? = null) : kotlin.collections.List<LiveChannel> {
        val localVarResponse = listLiveChannelsWithHttpInfo(group = group, favorites = favorites, recent = recent, hidden = hidden)

        return when (localVarResponse.responseType) {
            ResponseType.Success -> (localVarResponse as Success<*>).data as kotlin.collections.List<LiveChannel>
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
     * GET /livetv/channels
     * Channels in number order, with what&#39;s on now and next.
     * 
     * @param group Only this group (category). (optional)
     * @param favorites Only the caller&#39;s favourites. (optional)
     * @param recent The channels the caller watched last, newest first (LIVE-4). (optional)
     * @param hidden Only the channels the caller hid (otherwise they&#39;re left out). (optional)
     * @return ApiResponse<kotlin.collections.List<LiveChannel>?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class)
    fun listLiveChannelsWithHttpInfo(group: kotlin.String?, favorites: kotlin.Boolean?, recent: kotlin.Boolean?, hidden: kotlin.Boolean?) : ApiResponse<kotlin.collections.List<LiveChannel>?> {
        val localVariableConfig = listLiveChannelsRequestConfig(group = group, favorites = favorites, recent = recent, hidden = hidden)

        return request<Unit, kotlin.collections.List<LiveChannel>>(
            localVariableConfig
        )
    }

    /**
     * To obtain the request config of the operation listLiveChannels
     *
     * @param group Only this group (category). (optional)
     * @param favorites Only the caller&#39;s favourites. (optional)
     * @param recent The channels the caller watched last, newest first (LIVE-4). (optional)
     * @param hidden Only the channels the caller hid (otherwise they&#39;re left out). (optional)
     * @return RequestConfig
     */
    fun listLiveChannelsRequestConfig(group: kotlin.String?, favorites: kotlin.Boolean?, recent: kotlin.Boolean?, hidden: kotlin.Boolean?) : RequestConfig<Unit> {
        val localVariableBody = null
        val localVariableQuery: MultiValueMap = mutableMapOf<kotlin.String, kotlin.collections.List<kotlin.String>>()
            .apply {
                if (group != null) {
                    put("group", listOf(group.toString()))
                }
                if (favorites != null) {
                    put("favorites", listOf(favorites.toString()))
                }
                if (recent != null) {
                    put("recent", listOf(recent.toString()))
                }
                if (hidden != null) {
                    put("hidden", listOf(hidden.toString()))
                }
            }
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        localVariableHeaders["Accept"] = "application/json"

        return RequestConfig(
            method = RequestMethod.GET,
            path = "/livetv/channels",
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
            body = localVariableBody
        )
    }

    /**
     * GET /livetv/groups
     * Channel groups (categories) with their channel counts.
     * 
     * @return kotlin.collections.List<ListLiveGroups200ResponseInner>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    fun listLiveGroups() : kotlin.collections.List<ListLiveGroups200ResponseInner> {
        val localVarResponse = listLiveGroupsWithHttpInfo()

        return when (localVarResponse.responseType) {
            ResponseType.Success -> (localVarResponse as Success<*>).data as kotlin.collections.List<ListLiveGroups200ResponseInner>
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
     * GET /livetv/groups
     * Channel groups (categories) with their channel counts.
     * 
     * @return ApiResponse<kotlin.collections.List<ListLiveGroups200ResponseInner>?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class)
    fun listLiveGroupsWithHttpInfo() : ApiResponse<kotlin.collections.List<ListLiveGroups200ResponseInner>?> {
        val localVariableConfig = listLiveGroupsRequestConfig()

        return request<Unit, kotlin.collections.List<ListLiveGroups200ResponseInner>>(
            localVariableConfig
        )
    }

    /**
     * To obtain the request config of the operation listLiveGroups
     *
     * @return RequestConfig
     */
    fun listLiveGroupsRequestConfig() : RequestConfig<Unit> {
        val localVariableBody = null
        val localVariableQuery: MultiValueMap = mutableMapOf()
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        localVariableHeaders["Accept"] = "application/json"

        return RequestConfig(
            method = RequestMethod.GET,
            path = "/livetv/groups",
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
            body = localVariableBody
        )
    }

    /**
     * GET /livetv/recording-rules
     * Series being recorded.
     * 
     * @return kotlin.collections.List<RecordingRule>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    fun listRecordingRules() : kotlin.collections.List<RecordingRule> {
        val localVarResponse = listRecordingRulesWithHttpInfo()

        return when (localVarResponse.responseType) {
            ResponseType.Success -> (localVarResponse as Success<*>).data as kotlin.collections.List<RecordingRule>
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
     * GET /livetv/recording-rules
     * Series being recorded.
     * 
     * @return ApiResponse<kotlin.collections.List<RecordingRule>?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class)
    fun listRecordingRulesWithHttpInfo() : ApiResponse<kotlin.collections.List<RecordingRule>?> {
        val localVariableConfig = listRecordingRulesRequestConfig()

        return request<Unit, kotlin.collections.List<RecordingRule>>(
            localVariableConfig
        )
    }

    /**
     * To obtain the request config of the operation listRecordingRules
     *
     * @return RequestConfig
     */
    fun listRecordingRulesRequestConfig() : RequestConfig<Unit> {
        val localVariableBody = null
        val localVariableQuery: MultiValueMap = mutableMapOf()
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        localVariableHeaders["Accept"] = "application/json"

        return RequestConfig(
            method = RequestMethod.GET,
            path = "/livetv/recording-rules",
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
            body = localVariableBody
        )
    }

    /**
     * GET /livetv/recordings
     * DVR (LIVE-5): recordings in progress, upcoming (soonest first) and finished (newest first).
     * 
     * @return kotlin.collections.List<Recording>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    fun listRecordings() : kotlin.collections.List<Recording> {
        val localVarResponse = listRecordingsWithHttpInfo()

        return when (localVarResponse.responseType) {
            ResponseType.Success -> (localVarResponse as Success<*>).data as kotlin.collections.List<Recording>
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
     * GET /livetv/recordings
     * DVR (LIVE-5): recordings in progress, upcoming (soonest first) and finished (newest first).
     * 
     * @return ApiResponse<kotlin.collections.List<Recording>?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class)
    fun listRecordingsWithHttpInfo() : ApiResponse<kotlin.collections.List<Recording>?> {
        val localVariableConfig = listRecordingsRequestConfig()

        return request<Unit, kotlin.collections.List<Recording>>(
            localVariableConfig
        )
    }

    /**
     * To obtain the request config of the operation listRecordings
     *
     * @return RequestConfig
     */
    fun listRecordingsRequestConfig() : RequestConfig<Unit> {
        val localVariableBody = null
        val localVariableQuery: MultiValueMap = mutableMapOf()
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        localVariableHeaders["Accept"] = "application/json"

        return RequestConfig(
            method = RequestMethod.GET,
            path = "/livetv/recordings",
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
            body = localVariableBody
        )
    }

    /**
     * GET /livetv/channels/{channelId}/logo
     * The channel&#39;s logo, fetched from its source and cached (no sign-in needed, like artwork).
     * 
     * @param channelId 
     * @return java.io.File
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    fun liveChannelLogo(channelId: kotlin.Long) : java.io.File {
        val localVarResponse = liveChannelLogoWithHttpInfo(channelId = channelId)

        return when (localVarResponse.responseType) {
            ResponseType.Success -> (localVarResponse as Success<*>).data as java.io.File
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
     * GET /livetv/channels/{channelId}/logo
     * The channel&#39;s logo, fetched from its source and cached (no sign-in needed, like artwork).
     * 
     * @param channelId 
     * @return ApiResponse<java.io.File?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class)
    fun liveChannelLogoWithHttpInfo(channelId: kotlin.Long) : ApiResponse<java.io.File?> {
        val localVariableConfig = liveChannelLogoRequestConfig(channelId = channelId)

        return request<Unit, java.io.File>(
            localVariableConfig
        )
    }

    /**
     * To obtain the request config of the operation liveChannelLogo
     *
     * @param channelId 
     * @return RequestConfig
     */
    fun liveChannelLogoRequestConfig(channelId: kotlin.Long) : RequestConfig<Unit> {
        val localVariableBody = null
        val localVariableQuery: MultiValueMap = mutableMapOf()
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        localVariableHeaders["Accept"] = "application/json"

        return RequestConfig(
            method = RequestMethod.GET,
            path = "/livetv/channels/{channelId}/logo".replace("{"+"channelId"+"}", encodeURIComponent(channelId.toString())),
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = false,
            body = localVariableBody
        )
    }

    /**
     * GET /livetv/guide
     * The guide grid - programmes per channel between two times (at most 24 hours).
     * 
     * @param start 
     * @param end 
     * @param group  (optional)
     * @param favorites  (optional)
     * @param recent  (optional)
     * @return kotlin.collections.List<LiveGuide200ResponseInner>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    fun liveGuide(start: java.time.OffsetDateTime, end: java.time.OffsetDateTime, group: kotlin.String? = null, favorites: kotlin.Boolean? = null, recent: kotlin.Boolean? = null) : kotlin.collections.List<LiveGuide200ResponseInner> {
        val localVarResponse = liveGuideWithHttpInfo(start = start, end = end, group = group, favorites = favorites, recent = recent)

        return when (localVarResponse.responseType) {
            ResponseType.Success -> (localVarResponse as Success<*>).data as kotlin.collections.List<LiveGuide200ResponseInner>
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
     * GET /livetv/guide
     * The guide grid - programmes per channel between two times (at most 24 hours).
     * 
     * @param start 
     * @param end 
     * @param group  (optional)
     * @param favorites  (optional)
     * @param recent  (optional)
     * @return ApiResponse<kotlin.collections.List<LiveGuide200ResponseInner>?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class)
    fun liveGuideWithHttpInfo(start: java.time.OffsetDateTime, end: java.time.OffsetDateTime, group: kotlin.String?, favorites: kotlin.Boolean?, recent: kotlin.Boolean?) : ApiResponse<kotlin.collections.List<LiveGuide200ResponseInner>?> {
        val localVariableConfig = liveGuideRequestConfig(start = start, end = end, group = group, favorites = favorites, recent = recent)

        return request<Unit, kotlin.collections.List<LiveGuide200ResponseInner>>(
            localVariableConfig
        )
    }

    /**
     * To obtain the request config of the operation liveGuide
     *
     * @param start 
     * @param end 
     * @param group  (optional)
     * @param favorites  (optional)
     * @param recent  (optional)
     * @return RequestConfig
     */
    fun liveGuideRequestConfig(start: java.time.OffsetDateTime, end: java.time.OffsetDateTime, group: kotlin.String?, favorites: kotlin.Boolean?, recent: kotlin.Boolean?) : RequestConfig<Unit> {
        val localVariableBody = null
        val localVariableQuery: MultiValueMap = mutableMapOf<kotlin.String, kotlin.collections.List<kotlin.String>>()
            .apply {
                put("start", listOf(parseDateToQueryString<java.time.OffsetDateTime>(start)))
                put("end", listOf(parseDateToQueryString<java.time.OffsetDateTime>(end)))
                if (group != null) {
                    put("group", listOf(group.toString()))
                }
                if (favorites != null) {
                    put("favorites", listOf(favorites.toString()))
                }
                if (recent != null) {
                    put("recent", listOf(recent.toString()))
                }
            }
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        localVariableHeaders["Accept"] = "application/json"

        return RequestConfig(
            method = RequestMethod.GET,
            path = "/livetv/guide",
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
            body = localVariableBody
        )
    }

    /**
     * GET /livetv/status
     * Whether Live TV is set up, and how many channels there are.
     * 
     * @return LiveTvStatus
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    fun liveTvStatus() : LiveTvStatus {
        val localVarResponse = liveTvStatusWithHttpInfo()

        return when (localVarResponse.responseType) {
            ResponseType.Success -> (localVarResponse as Success<*>).data as LiveTvStatus
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
     * GET /livetv/status
     * Whether Live TV is set up, and how many channels there are.
     * 
     * @return ApiResponse<LiveTvStatus?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class)
    fun liveTvStatusWithHttpInfo() : ApiResponse<LiveTvStatus?> {
        val localVariableConfig = liveTvStatusRequestConfig()

        return request<Unit, LiveTvStatus>(
            localVariableConfig
        )
    }

    /**
     * To obtain the request config of the operation liveTvStatus
     *
     * @return RequestConfig
     */
    fun liveTvStatusRequestConfig() : RequestConfig<Unit> {
        val localVariableBody = null
        val localVariableQuery: MultiValueMap = mutableMapOf()
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        localVariableHeaders["Accept"] = "application/json"

        return RequestConfig(
            method = RequestMethod.GET,
            path = "/livetv/status",
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
            body = localVariableBody
        )
    }

    /**
     * POST /livetv/channels/{channelId}/play
     * Start watching a channel. Returns a live HLS session (copied or transcoded for the device).
     * 
     * @param channelId 
     * @param playLiveChannelRequest 
     * @return LiveSession
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    fun playLiveChannel(channelId: kotlin.Long, playLiveChannelRequest: PlayLiveChannelRequest) : LiveSession {
        val localVarResponse = playLiveChannelWithHttpInfo(channelId = channelId, playLiveChannelRequest = playLiveChannelRequest)

        return when (localVarResponse.responseType) {
            ResponseType.Success -> (localVarResponse as Success<*>).data as LiveSession
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
     * POST /livetv/channels/{channelId}/play
     * Start watching a channel. Returns a live HLS session (copied or transcoded for the device).
     * 
     * @param channelId 
     * @param playLiveChannelRequest 
     * @return ApiResponse<LiveSession?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class)
    fun playLiveChannelWithHttpInfo(channelId: kotlin.Long, playLiveChannelRequest: PlayLiveChannelRequest) : ApiResponse<LiveSession?> {
        val localVariableConfig = playLiveChannelRequestConfig(channelId = channelId, playLiveChannelRequest = playLiveChannelRequest)

        return request<PlayLiveChannelRequest, LiveSession>(
            localVariableConfig
        )
    }

    /**
     * To obtain the request config of the operation playLiveChannel
     *
     * @param channelId 
     * @param playLiveChannelRequest 
     * @return RequestConfig
     */
    fun playLiveChannelRequestConfig(channelId: kotlin.Long, playLiveChannelRequest: PlayLiveChannelRequest) : RequestConfig<PlayLiveChannelRequest> {
        val localVariableBody = playLiveChannelRequest
        val localVariableQuery: MultiValueMap = mutableMapOf()
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        localVariableHeaders["Content-Type"] = "application/json"
        localVariableHeaders["Accept"] = "application/json"

        return RequestConfig(
            method = RequestMethod.POST,
            path = "/livetv/channels/{channelId}/play".replace("{"+"channelId"+"}", encodeURIComponent(channelId.toString())),
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
            body = localVariableBody
        )
    }

    /**
     * POST /livetv/refresh
     * Reload channels and the guide from every source now (admin only).
     * 
     * @return LiveTvStatus
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    fun refreshLiveTv() : LiveTvStatus {
        val localVarResponse = refreshLiveTvWithHttpInfo()

        return when (localVarResponse.responseType) {
            ResponseType.Success -> (localVarResponse as Success<*>).data as LiveTvStatus
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
     * POST /livetv/refresh
     * Reload channels and the guide from every source now (admin only).
     * 
     * @return ApiResponse<LiveTvStatus?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class)
    fun refreshLiveTvWithHttpInfo() : ApiResponse<LiveTvStatus?> {
        val localVariableConfig = refreshLiveTvRequestConfig()

        return request<Unit, LiveTvStatus>(
            localVariableConfig
        )
    }

    /**
     * To obtain the request config of the operation refreshLiveTv
     *
     * @return RequestConfig
     */
    fun refreshLiveTvRequestConfig() : RequestConfig<Unit> {
        val localVariableBody = null
        val localVariableQuery: MultiValueMap = mutableMapOf()
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        localVariableHeaders["Accept"] = "application/json"

        return RequestConfig(
            method = RequestMethod.POST,
            path = "/livetv/refresh",
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
            body = localVariableBody
        )
    }

    /**
     * POST /livetv/recordings
     * Record a programme from the guide, or every airing of its title (a series).
     * 
     * @param scheduleRecordingRequest 
     * @return ScheduleRecording201Response
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    fun scheduleRecording(scheduleRecordingRequest: ScheduleRecordingRequest) : ScheduleRecording201Response {
        val localVarResponse = scheduleRecordingWithHttpInfo(scheduleRecordingRequest = scheduleRecordingRequest)

        return when (localVarResponse.responseType) {
            ResponseType.Success -> (localVarResponse as Success<*>).data as ScheduleRecording201Response
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
     * POST /livetv/recordings
     * Record a programme from the guide, or every airing of its title (a series).
     * 
     * @param scheduleRecordingRequest 
     * @return ApiResponse<ScheduleRecording201Response?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class)
    fun scheduleRecordingWithHttpInfo(scheduleRecordingRequest: ScheduleRecordingRequest) : ApiResponse<ScheduleRecording201Response?> {
        val localVariableConfig = scheduleRecordingRequestConfig(scheduleRecordingRequest = scheduleRecordingRequest)

        return request<ScheduleRecordingRequest, ScheduleRecording201Response>(
            localVariableConfig
        )
    }

    /**
     * To obtain the request config of the operation scheduleRecording
     *
     * @param scheduleRecordingRequest 
     * @return RequestConfig
     */
    fun scheduleRecordingRequestConfig(scheduleRecordingRequest: ScheduleRecordingRequest) : RequestConfig<ScheduleRecordingRequest> {
        val localVariableBody = scheduleRecordingRequest
        val localVariableQuery: MultiValueMap = mutableMapOf()
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        localVariableHeaders["Content-Type"] = "application/json"
        localVariableHeaders["Accept"] = "application/json"

        return RequestConfig(
            method = RequestMethod.POST,
            path = "/livetv/recordings",
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
            body = localVariableBody
        )
    }

    /**
     * DELETE /livetv/sessions/{sessionId}
     * Stop watching (the stream also stops by itself when nothing fetches it for a minute).
     * 
     * @param sessionId 
     * @return void
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    fun stopLiveSession(sessionId: kotlin.String) : Unit {
        val localVarResponse = stopLiveSessionWithHttpInfo(sessionId = sessionId)

        return when (localVarResponse.responseType) {
            ResponseType.Success -> Unit
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
     * DELETE /livetv/sessions/{sessionId}
     * Stop watching (the stream also stops by itself when nothing fetches it for a minute).
     * 
     * @param sessionId 
     * @return ApiResponse<Unit?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Throws(IllegalStateException::class, IOException::class)
    fun stopLiveSessionWithHttpInfo(sessionId: kotlin.String) : ApiResponse<Unit?> {
        val localVariableConfig = stopLiveSessionRequestConfig(sessionId = sessionId)

        return request<Unit, Unit>(
            localVariableConfig
        )
    }

    /**
     * To obtain the request config of the operation stopLiveSession
     *
     * @param sessionId 
     * @return RequestConfig
     */
    fun stopLiveSessionRequestConfig(sessionId: kotlin.String) : RequestConfig<Unit> {
        val localVariableBody = null
        val localVariableQuery: MultiValueMap = mutableMapOf()
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        localVariableHeaders["Accept"] = "application/json"

        return RequestConfig(
            method = RequestMethod.DELETE,
            path = "/livetv/sessions/{sessionId}".replace("{"+"sessionId"+"}", encodeURIComponent(sessionId.toString())),
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
            body = localVariableBody
        )
    }

    /**
     * DELETE /livetv/channels/{channelId}/favorite
     * Remove a channel from the caller&#39;s favourites.
     * 
     * @param channelId 
     * @return void
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    fun unfavoriteLiveChannel(channelId: kotlin.Long) : Unit {
        val localVarResponse = unfavoriteLiveChannelWithHttpInfo(channelId = channelId)

        return when (localVarResponse.responseType) {
            ResponseType.Success -> Unit
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
     * DELETE /livetv/channels/{channelId}/favorite
     * Remove a channel from the caller&#39;s favourites.
     * 
     * @param channelId 
     * @return ApiResponse<Unit?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Throws(IllegalStateException::class, IOException::class)
    fun unfavoriteLiveChannelWithHttpInfo(channelId: kotlin.Long) : ApiResponse<Unit?> {
        val localVariableConfig = unfavoriteLiveChannelRequestConfig(channelId = channelId)

        return request<Unit, Unit>(
            localVariableConfig
        )
    }

    /**
     * To obtain the request config of the operation unfavoriteLiveChannel
     *
     * @param channelId 
     * @return RequestConfig
     */
    fun unfavoriteLiveChannelRequestConfig(channelId: kotlin.Long) : RequestConfig<Unit> {
        val localVariableBody = null
        val localVariableQuery: MultiValueMap = mutableMapOf()
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        localVariableHeaders["Accept"] = "application/json"

        return RequestConfig(
            method = RequestMethod.DELETE,
            path = "/livetv/channels/{channelId}/favorite".replace("{"+"channelId"+"}", encodeURIComponent(channelId.toString())),
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
            body = localVariableBody
        )
    }

    /**
     * DELETE /livetv/channels/{channelId}/hidden
     * Show a hidden channel again.
     * 
     * @param channelId 
     * @return void
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    fun unhideLiveChannel(channelId: kotlin.Long) : Unit {
        val localVarResponse = unhideLiveChannelWithHttpInfo(channelId = channelId)

        return when (localVarResponse.responseType) {
            ResponseType.Success -> Unit
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
     * DELETE /livetv/channels/{channelId}/hidden
     * Show a hidden channel again.
     * 
     * @param channelId 
     * @return ApiResponse<Unit?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Throws(IllegalStateException::class, IOException::class)
    fun unhideLiveChannelWithHttpInfo(channelId: kotlin.Long) : ApiResponse<Unit?> {
        val localVariableConfig = unhideLiveChannelRequestConfig(channelId = channelId)

        return request<Unit, Unit>(
            localVariableConfig
        )
    }

    /**
     * To obtain the request config of the operation unhideLiveChannel
     *
     * @param channelId 
     * @return RequestConfig
     */
    fun unhideLiveChannelRequestConfig(channelId: kotlin.Long) : RequestConfig<Unit> {
        val localVariableBody = null
        val localVariableQuery: MultiValueMap = mutableMapOf()
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        localVariableHeaders["Accept"] = "application/json"

        return RequestConfig(
            method = RequestMethod.DELETE,
            path = "/livetv/channels/{channelId}/hidden".replace("{"+"channelId"+"}", encodeURIComponent(channelId.toString())),
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
            body = localVariableBody
        )
    }


    private fun encodeURIComponent(uriComponent: kotlin.String): kotlin.String =
        HttpUrl.Builder().scheme("http").host("localhost").addPathSegment(uriComponent).build().encodedPathSegments[0]
}
