/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package app.marquee.api.apis

import java.io.IOException
import okhttp3.Call
import okhttp3.HttpUrl

import app.marquee.api.models.DownloadSubtitle201Response
import app.marquee.api.models.DownloadSubtitleRequest
import app.marquee.api.models.Error
import app.marquee.api.models.ItemSummary
import app.marquee.api.models.PlaybackProgress
import app.marquee.api.models.PlaybackRequest
import app.marquee.api.models.PlaybackSession
import app.marquee.api.models.PlaybackSessionInfo
import app.marquee.api.models.SubtitleResult
import app.marquee.api.models.SyncProgressRequest
import app.marquee.api.models.Trickplay

import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

import app.marquee.api.infrastructure.ApiClient
import app.marquee.api.infrastructure.ApiResponse
import app.marquee.api.infrastructure.ClientException
import app.marquee.api.infrastructure.ClientError
import app.marquee.api.infrastructure.ServerException
import app.marquee.api.infrastructure.ServerError
import app.marquee.api.infrastructure.MultiValueMap
import app.marquee.api.infrastructure.PartConfig
import app.marquee.api.infrastructure.RequestConfig
import app.marquee.api.infrastructure.RequestMethod
import app.marquee.api.infrastructure.ResponseType
import app.marquee.api.infrastructure.Success
import app.marquee.api.infrastructure.toMultiValue
import app.marquee.api.infrastructure.Serializer

open class PlaybackApi(basePath: kotlin.String = defaultBasePath, client: Call.Factory = ApiClient.defaultClient) : ApiClient(basePath, client) {
    companion object {
        @JvmStatic
        val defaultBasePath: String by lazy {
            System.getProperties().getProperty(ApiClient.BASE_URL_KEY, "/api/v1")
        }
    }

    /**
     * GET /playback/bandwidth-test
     * Random bytes for the client to time its download speed (used for automatic remote quality).
     * 
     * @param kb  (optional, default to 1024)
     * @return java.io.File
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    fun bandwidthTest(kb: kotlin.Int? = 1024) : java.io.File {
        val localVarResponse = bandwidthTestWithHttpInfo(kb = kb)

        return when (localVarResponse.responseType) {
            ResponseType.Success -> (localVarResponse as Success<*>).data as java.io.File
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
     * GET /playback/bandwidth-test
     * Random bytes for the client to time its download speed (used for automatic remote quality).
     * 
     * @param kb  (optional, default to 1024)
     * @return ApiResponse<java.io.File?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class)
    fun bandwidthTestWithHttpInfo(kb: kotlin.Int?) : ApiResponse<java.io.File?> {
        val localVariableConfig = bandwidthTestRequestConfig(kb = kb)

        return request<Unit, java.io.File>(
            localVariableConfig
        )
    }

    /**
     * To obtain the request config of the operation bandwidthTest
     *
     * @param kb  (optional, default to 1024)
     * @return RequestConfig
     */
    fun bandwidthTestRequestConfig(kb: kotlin.Int?) : RequestConfig<Unit> {
        val localVariableBody = null
        val localVariableQuery: MultiValueMap = mutableMapOf<kotlin.String, kotlin.collections.List<kotlin.String>>()
            .apply {
                if (kb != null) {
                    put("kb", listOf(kb.toString()))
                }
            }
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        localVariableHeaders["Accept"] = "application/octet-stream, application/json"

        return RequestConfig(
            method = RequestMethod.GET,
            path = "/playback/bandwidth-test",
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
            body = localVariableBody
        )
    }

    /**
     * POST /items/{itemId}/subtitles
     * Download a subtitle from OpenSubtitles and add it to the item&#39;s subtitle choices.
     * 
     * @param itemId 
     * @param downloadSubtitleRequest 
     * @return DownloadSubtitle201Response
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    fun downloadSubtitle(itemId: kotlin.Long, downloadSubtitleRequest: DownloadSubtitleRequest) : DownloadSubtitle201Response {
        val localVarResponse = downloadSubtitleWithHttpInfo(itemId = itemId, downloadSubtitleRequest = downloadSubtitleRequest)

        return when (localVarResponse.responseType) {
            ResponseType.Success -> (localVarResponse as Success<*>).data as DownloadSubtitle201Response
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
     * POST /items/{itemId}/subtitles
     * Download a subtitle from OpenSubtitles and add it to the item&#39;s subtitle choices.
     * 
     * @param itemId 
     * @param downloadSubtitleRequest 
     * @return ApiResponse<DownloadSubtitle201Response?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class)
    fun downloadSubtitleWithHttpInfo(itemId: kotlin.Long, downloadSubtitleRequest: DownloadSubtitleRequest) : ApiResponse<DownloadSubtitle201Response?> {
        val localVariableConfig = downloadSubtitleRequestConfig(itemId = itemId, downloadSubtitleRequest = downloadSubtitleRequest)

        return request<DownloadSubtitleRequest, DownloadSubtitle201Response>(
            localVariableConfig
        )
    }

    /**
     * To obtain the request config of the operation downloadSubtitle
     *
     * @param itemId 
     * @param downloadSubtitleRequest 
     * @return RequestConfig
     */
    fun downloadSubtitleRequestConfig(itemId: kotlin.Long, downloadSubtitleRequest: DownloadSubtitleRequest) : RequestConfig<DownloadSubtitleRequest> {
        val localVariableBody = downloadSubtitleRequest
        val localVariableQuery: MultiValueMap = mutableMapOf()
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        localVariableHeaders["Content-Type"] = "application/json"
        localVariableHeaders["Accept"] = "application/json"

        return RequestConfig(
            method = RequestMethod.POST,
            path = "/items/{itemId}/subtitles".replace("{"+"itemId"+"}", encodeURIComponent(itemId.toString())),
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
            body = localVariableBody
        )
    }

    /**
     * GET /items/{itemId}/trickplay
     * Seek-bar preview thumbnails for a video (PLAY-13), as sprite sheets of columns × rows tiles.
     * 
     * @param itemId 
     * @return Trickplay
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    fun getTrickplay(itemId: kotlin.Long) : Trickplay {
        val localVarResponse = getTrickplayWithHttpInfo(itemId = itemId)

        return when (localVarResponse.responseType) {
            ResponseType.Success -> (localVarResponse as Success<*>).data as Trickplay
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
     * GET /items/{itemId}/trickplay
     * Seek-bar preview thumbnails for a video (PLAY-13), as sprite sheets of columns × rows tiles.
     * 
     * @param itemId 
     * @return ApiResponse<Trickplay?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class)
    fun getTrickplayWithHttpInfo(itemId: kotlin.Long) : ApiResponse<Trickplay?> {
        val localVariableConfig = getTrickplayRequestConfig(itemId = itemId)

        return request<Unit, Trickplay>(
            localVariableConfig
        )
    }

    /**
     * To obtain the request config of the operation getTrickplay
     *
     * @param itemId 
     * @return RequestConfig
     */
    fun getTrickplayRequestConfig(itemId: kotlin.Long) : RequestConfig<Unit> {
        val localVariableBody = null
        val localVariableQuery: MultiValueMap = mutableMapOf()
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        localVariableHeaders["Accept"] = "application/json"

        return RequestConfig(
            method = RequestMethod.GET,
            path = "/items/{itemId}/trickplay".replace("{"+"itemId"+"}", encodeURIComponent(itemId.toString())),
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
            body = localVariableBody
        )
    }

    /**
     * GET /items/{itemId}/trickplay/{sheet}
     * One sprite sheet; thumbnail n is on sheet n / (columns × rows).
     * 
     * @param itemId 
     * @param sheet 
     * @return java.io.File
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    fun getTrickplaySheet(itemId: kotlin.Long, sheet: kotlin.Int) : java.io.File {
        val localVarResponse = getTrickplaySheetWithHttpInfo(itemId = itemId, sheet = sheet)

        return when (localVarResponse.responseType) {
            ResponseType.Success -> (localVarResponse as Success<*>).data as java.io.File
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
     * GET /items/{itemId}/trickplay/{sheet}
     * One sprite sheet; thumbnail n is on sheet n / (columns × rows).
     * 
     * @param itemId 
     * @param sheet 
     * @return ApiResponse<java.io.File?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class)
    fun getTrickplaySheetWithHttpInfo(itemId: kotlin.Long, sheet: kotlin.Int) : ApiResponse<java.io.File?> {
        val localVariableConfig = getTrickplaySheetRequestConfig(itemId = itemId, sheet = sheet)

        return request<Unit, java.io.File>(
            localVariableConfig
        )
    }

    /**
     * To obtain the request config of the operation getTrickplaySheet
     *
     * @param itemId 
     * @param sheet 
     * @return RequestConfig
     */
    fun getTrickplaySheetRequestConfig(itemId: kotlin.Long, sheet: kotlin.Int) : RequestConfig<Unit> {
        val localVariableBody = null
        val localVariableQuery: MultiValueMap = mutableMapOf()
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        localVariableHeaders["Accept"] = "application/json"

        return RequestConfig(
            method = RequestMethod.GET,
            path = "/items/{itemId}/trickplay/{sheet}".replace("{"+"itemId"+"}", encodeURIComponent(itemId.toString())).replace("{"+"sheet"+"}", encodeURIComponent(sheet.toString())),
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
            body = localVariableBody
        )
    }

    /**
     * GET /playback/sessions
     * Active playback sessions. Administrators see everyone&#39;s; others see their own.
     * 
     * @return kotlin.collections.List<PlaybackSessionInfo>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    fun listPlaybackSessions() : kotlin.collections.List<PlaybackSessionInfo> {
        val localVarResponse = listPlaybackSessionsWithHttpInfo()

        return when (localVarResponse.responseType) {
            ResponseType.Success -> (localVarResponse as Success<*>).data as kotlin.collections.List<PlaybackSessionInfo>
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
     * GET /playback/sessions
     * Active playback sessions. Administrators see everyone&#39;s; others see their own.
     * 
     * @return ApiResponse<kotlin.collections.List<PlaybackSessionInfo>?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class)
    fun listPlaybackSessionsWithHttpInfo() : ApiResponse<kotlin.collections.List<PlaybackSessionInfo>?> {
        val localVariableConfig = listPlaybackSessionsRequestConfig()

        return request<Unit, kotlin.collections.List<PlaybackSessionInfo>>(
            localVariableConfig
        )
    }

    /**
     * To obtain the request config of the operation listPlaybackSessions
     *
     * @return RequestConfig
     */
    fun listPlaybackSessionsRequestConfig() : RequestConfig<Unit> {
        val localVariableBody = null
        val localVariableQuery: MultiValueMap = mutableMapOf()
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        localVariableHeaders["Accept"] = "application/json"

        return RequestConfig(
            method = RequestMethod.GET,
            path = "/playback/sessions",
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
            body = localVariableBody
        )
    }

    /**
     * GET /items/{itemId}/prerolls
     * What to play before a movie (PLAY-18): trailers of other movies, then the pre-roll video. Empty when off, for non-movies, or when the person opted out. Call it only when starting from the beginning.
     * 
     * @param itemId 
     * @return kotlin.collections.List<ItemSummary>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    fun listPrerolls(itemId: kotlin.Long) : kotlin.collections.List<ItemSummary> {
        val localVarResponse = listPrerollsWithHttpInfo(itemId = itemId)

        return when (localVarResponse.responseType) {
            ResponseType.Success -> (localVarResponse as Success<*>).data as kotlin.collections.List<ItemSummary>
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
     * GET /items/{itemId}/prerolls
     * What to play before a movie (PLAY-18): trailers of other movies, then the pre-roll video. Empty when off, for non-movies, or when the person opted out. Call it only when starting from the beginning.
     * 
     * @param itemId 
     * @return ApiResponse<kotlin.collections.List<ItemSummary>?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class)
    fun listPrerollsWithHttpInfo(itemId: kotlin.Long) : ApiResponse<kotlin.collections.List<ItemSummary>?> {
        val localVariableConfig = listPrerollsRequestConfig(itemId = itemId)

        return request<Unit, kotlin.collections.List<ItemSummary>>(
            localVariableConfig
        )
    }

    /**
     * To obtain the request config of the operation listPrerolls
     *
     * @param itemId 
     * @return RequestConfig
     */
    fun listPrerollsRequestConfig(itemId: kotlin.Long) : RequestConfig<Unit> {
        val localVariableBody = null
        val localVariableQuery: MultiValueMap = mutableMapOf()
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        localVariableHeaders["Accept"] = "application/json"

        return RequestConfig(
            method = RequestMethod.GET,
            path = "/items/{itemId}/prerolls".replace("{"+"itemId"+"}", encodeURIComponent(itemId.toString())),
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
            body = localVariableBody
        )
    }

    /**
     * DELETE /items/{itemId}/subtitles/{streamId}
     * Remove a downloaded subtitle (admin only).
     * 
     * @param itemId 
     * @param streamId 
     * @return void
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    fun removeSubtitle(itemId: kotlin.Long, streamId: kotlin.Long) : Unit {
        val localVarResponse = removeSubtitleWithHttpInfo(itemId = itemId, streamId = streamId)

        return when (localVarResponse.responseType) {
            ResponseType.Success -> Unit
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
     * DELETE /items/{itemId}/subtitles/{streamId}
     * Remove a downloaded subtitle (admin only).
     * 
     * @param itemId 
     * @param streamId 
     * @return ApiResponse<Unit?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Throws(IllegalStateException::class, IOException::class)
    fun removeSubtitleWithHttpInfo(itemId: kotlin.Long, streamId: kotlin.Long) : ApiResponse<Unit?> {
        val localVariableConfig = removeSubtitleRequestConfig(itemId = itemId, streamId = streamId)

        return request<Unit, Unit>(
            localVariableConfig
        )
    }

    /**
     * To obtain the request config of the operation removeSubtitle
     *
     * @param itemId 
     * @param streamId 
     * @return RequestConfig
     */
    fun removeSubtitleRequestConfig(itemId: kotlin.Long, streamId: kotlin.Long) : RequestConfig<Unit> {
        val localVariableBody = null
        val localVariableQuery: MultiValueMap = mutableMapOf()
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        localVariableHeaders["Accept"] = "application/json"

        return RequestConfig(
            method = RequestMethod.DELETE,
            path = "/items/{itemId}/subtitles/{streamId}".replace("{"+"itemId"+"}", encodeURIComponent(itemId.toString())).replace("{"+"streamId"+"}", encodeURIComponent(streamId.toString())),
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
            body = localVariableBody
        )
    }

    /**
     * PATCH /playback/sessions/{sessionId}
     * Report position and state (every ~10 seconds, and on pause/seek). Updates resume points and watched status.
     * 
     * @param sessionId 
     * @param playbackProgress 
     * @return void
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    fun reportPlayback(sessionId: kotlin.String, playbackProgress: PlaybackProgress) : Unit {
        val localVarResponse = reportPlaybackWithHttpInfo(sessionId = sessionId, playbackProgress = playbackProgress)

        return when (localVarResponse.responseType) {
            ResponseType.Success -> Unit
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
     * PATCH /playback/sessions/{sessionId}
     * Report position and state (every ~10 seconds, and on pause/seek). Updates resume points and watched status.
     * 
     * @param sessionId 
     * @param playbackProgress 
     * @return ApiResponse<Unit?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Throws(IllegalStateException::class, IOException::class)
    fun reportPlaybackWithHttpInfo(sessionId: kotlin.String, playbackProgress: PlaybackProgress) : ApiResponse<Unit?> {
        val localVariableConfig = reportPlaybackRequestConfig(sessionId = sessionId, playbackProgress = playbackProgress)

        return request<PlaybackProgress, Unit>(
            localVariableConfig
        )
    }

    /**
     * To obtain the request config of the operation reportPlayback
     *
     * @param sessionId 
     * @param playbackProgress 
     * @return RequestConfig
     */
    fun reportPlaybackRequestConfig(sessionId: kotlin.String, playbackProgress: PlaybackProgress) : RequestConfig<PlaybackProgress> {
        val localVariableBody = playbackProgress
        val localVariableQuery: MultiValueMap = mutableMapOf()
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        localVariableHeaders["Content-Type"] = "application/json"
        localVariableHeaders["Accept"] = "application/json"

        return RequestConfig(
            method = RequestMethod.PATCH,
            path = "/playback/sessions/{sessionId}".replace("{"+"sessionId"+"}", encodeURIComponent(sessionId.toString())),
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
            body = localVariableBody
        )
    }

    /**
     * GET /items/{itemId}/subtitles/search
     * Search OpenSubtitles for a movie&#39;s or episode&#39;s subtitles (PLAY-7). Results made for this exact file come first.
     * 
     * @param itemId 
     * @param languages Comma-separated ISO 639-1 codes, e.g. \&quot;en,es\&quot;. (optional, default to "en")
     * @return kotlin.collections.List<SubtitleResult>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    fun searchSubtitles(itemId: kotlin.Long, languages: kotlin.String? = "en") : kotlin.collections.List<SubtitleResult> {
        val localVarResponse = searchSubtitlesWithHttpInfo(itemId = itemId, languages = languages)

        return when (localVarResponse.responseType) {
            ResponseType.Success -> (localVarResponse as Success<*>).data as kotlin.collections.List<SubtitleResult>
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
     * GET /items/{itemId}/subtitles/search
     * Search OpenSubtitles for a movie&#39;s or episode&#39;s subtitles (PLAY-7). Results made for this exact file come first.
     * 
     * @param itemId 
     * @param languages Comma-separated ISO 639-1 codes, e.g. \&quot;en,es\&quot;. (optional, default to "en")
     * @return ApiResponse<kotlin.collections.List<SubtitleResult>?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class)
    fun searchSubtitlesWithHttpInfo(itemId: kotlin.Long, languages: kotlin.String?) : ApiResponse<kotlin.collections.List<SubtitleResult>?> {
        val localVariableConfig = searchSubtitlesRequestConfig(itemId = itemId, languages = languages)

        return request<Unit, kotlin.collections.List<SubtitleResult>>(
            localVariableConfig
        )
    }

    /**
     * To obtain the request config of the operation searchSubtitles
     *
     * @param itemId 
     * @param languages Comma-separated ISO 639-1 codes, e.g. \&quot;en,es\&quot;. (optional, default to "en")
     * @return RequestConfig
     */
    fun searchSubtitlesRequestConfig(itemId: kotlin.Long, languages: kotlin.String?) : RequestConfig<Unit> {
        val localVariableBody = null
        val localVariableQuery: MultiValueMap = mutableMapOf<kotlin.String, kotlin.collections.List<kotlin.String>>()
            .apply {
                if (languages != null) {
                    put("languages", listOf(languages.toString()))
                }
            }
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        localVariableHeaders["Accept"] = "application/json"

        return RequestConfig(
            method = RequestMethod.GET,
            path = "/items/{itemId}/subtitles/search".replace("{"+"itemId"+"}", encodeURIComponent(itemId.toString())),
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
            body = localVariableBody
        )
    }

    /**
     * POST /playback/sessions
     * Start playing an item. The server decides between direct play, direct stream and transcode for this device and network.
     * 
     * @param playbackRequest 
     * @return PlaybackSession
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    fun startPlayback(playbackRequest: PlaybackRequest) : PlaybackSession {
        val localVarResponse = startPlaybackWithHttpInfo(playbackRequest = playbackRequest)

        return when (localVarResponse.responseType) {
            ResponseType.Success -> (localVarResponse as Success<*>).data as PlaybackSession
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
     * POST /playback/sessions
     * Start playing an item. The server decides between direct play, direct stream and transcode for this device and network.
     * 
     * @param playbackRequest 
     * @return ApiResponse<PlaybackSession?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class)
    fun startPlaybackWithHttpInfo(playbackRequest: PlaybackRequest) : ApiResponse<PlaybackSession?> {
        val localVariableConfig = startPlaybackRequestConfig(playbackRequest = playbackRequest)

        return request<PlaybackRequest, PlaybackSession>(
            localVariableConfig
        )
    }

    /**
     * To obtain the request config of the operation startPlayback
     *
     * @param playbackRequest 
     * @return RequestConfig
     */
    fun startPlaybackRequestConfig(playbackRequest: PlaybackRequest) : RequestConfig<PlaybackRequest> {
        val localVariableBody = playbackRequest
        val localVariableQuery: MultiValueMap = mutableMapOf()
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        localVariableHeaders["Content-Type"] = "application/json"
        localVariableHeaders["Accept"] = "application/json"

        return RequestConfig(
            method = RequestMethod.POST,
            path = "/playback/sessions",
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
            body = localVariableBody
        )
    }

    /**
     * DELETE /playback/sessions/{sessionId}
     * Stop playback. Administrators can stop anyone&#39;s session.
     * 
     * @param sessionId 
     * @return void
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    fun stopPlayback(sessionId: kotlin.String) : Unit {
        val localVarResponse = stopPlaybackWithHttpInfo(sessionId = sessionId)

        return when (localVarResponse.responseType) {
            ResponseType.Success -> Unit
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
     * DELETE /playback/sessions/{sessionId}
     * Stop playback. Administrators can stop anyone&#39;s session.
     * 
     * @param sessionId 
     * @return ApiResponse<Unit?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Throws(IllegalStateException::class, IOException::class)
    fun stopPlaybackWithHttpInfo(sessionId: kotlin.String) : ApiResponse<Unit?> {
        val localVariableConfig = stopPlaybackRequestConfig(sessionId = sessionId)

        return request<Unit, Unit>(
            localVariableConfig
        )
    }

    /**
     * To obtain the request config of the operation stopPlayback
     *
     * @param sessionId 
     * @return RequestConfig
     */
    fun stopPlaybackRequestConfig(sessionId: kotlin.String) : RequestConfig<Unit> {
        val localVariableBody = null
        val localVariableQuery: MultiValueMap = mutableMapOf()
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        localVariableHeaders["Accept"] = "application/json"

        return RequestConfig(
            method = RequestMethod.DELETE,
            path = "/playback/sessions/{sessionId}".replace("{"+"sessionId"+"}", encodeURIComponent(sessionId.toString())),
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
            body = localVariableBody
        )
    }

    /**
     * PUT /items/{itemId}/progress
     * Record progress made while offline (a downloaded item played without a session).
     * 
     * @param itemId 
     * @param syncProgressRequest 
     * @return void
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    fun syncProgress(itemId: kotlin.Long, syncProgressRequest: SyncProgressRequest) : Unit {
        val localVarResponse = syncProgressWithHttpInfo(itemId = itemId, syncProgressRequest = syncProgressRequest)

        return when (localVarResponse.responseType) {
            ResponseType.Success -> Unit
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
     * PUT /items/{itemId}/progress
     * Record progress made while offline (a downloaded item played without a session).
     * 
     * @param itemId 
     * @param syncProgressRequest 
     * @return ApiResponse<Unit?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Throws(IllegalStateException::class, IOException::class)
    fun syncProgressWithHttpInfo(itemId: kotlin.Long, syncProgressRequest: SyncProgressRequest) : ApiResponse<Unit?> {
        val localVariableConfig = syncProgressRequestConfig(itemId = itemId, syncProgressRequest = syncProgressRequest)

        return request<SyncProgressRequest, Unit>(
            localVariableConfig
        )
    }

    /**
     * To obtain the request config of the operation syncProgress
     *
     * @param itemId 
     * @param syncProgressRequest 
     * @return RequestConfig
     */
    fun syncProgressRequestConfig(itemId: kotlin.Long, syncProgressRequest: SyncProgressRequest) : RequestConfig<SyncProgressRequest> {
        val localVariableBody = syncProgressRequest
        val localVariableQuery: MultiValueMap = mutableMapOf()
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        localVariableHeaders["Content-Type"] = "application/json"
        localVariableHeaders["Accept"] = "application/json"

        return RequestConfig(
            method = RequestMethod.PUT,
            path = "/items/{itemId}/progress".replace("{"+"itemId"+"}", encodeURIComponent(itemId.toString())),
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
            body = localVariableBody
        )
    }


    private fun encodeURIComponent(uriComponent: kotlin.String): kotlin.String =
        HttpUrl.Builder().scheme("http").host("localhost").addPathSegment(uriComponent).build().encodedPathSegments[0]
}
