/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package app.marquee.api.apis

import java.io.IOException
import okhttp3.Call
import okhttp3.HttpUrl

import app.marquee.api.models.CreateWatchGroupRequest
import app.marquee.api.models.Error
import app.marquee.api.models.WatchGroup
import app.marquee.api.models.WatchGroupCommandRequest

import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

import app.marquee.api.infrastructure.ApiClient
import app.marquee.api.infrastructure.ApiResponse
import app.marquee.api.infrastructure.ClientException
import app.marquee.api.infrastructure.ClientError
import app.marquee.api.infrastructure.ServerException
import app.marquee.api.infrastructure.ServerError
import app.marquee.api.infrastructure.MultiValueMap
import app.marquee.api.infrastructure.PartConfig
import app.marquee.api.infrastructure.RequestConfig
import app.marquee.api.infrastructure.RequestMethod
import app.marquee.api.infrastructure.ResponseType
import app.marquee.api.infrastructure.Success
import app.marquee.api.infrastructure.toMultiValue
import app.marquee.api.infrastructure.Serializer

open class SyncplayApi(basePath: kotlin.String = defaultBasePath, client: Call.Factory = ApiClient.defaultClient) : ApiClient(basePath, client) {
    companion object {
        @JvmStatic
        val defaultBasePath: String by lazy {
            System.getProperties().getProperty(ApiClient.BASE_URL_KEY, "/api/v1")
        }
    }

    /**
     * POST /syncplay/groups
     * Start watching something together; the caller is the first member.
     * 
     * @param createWatchGroupRequest 
     * @return WatchGroup
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    fun createWatchGroup(createWatchGroupRequest: CreateWatchGroupRequest) : WatchGroup {
        val localVarResponse = createWatchGroupWithHttpInfo(createWatchGroupRequest = createWatchGroupRequest)

        return when (localVarResponse.responseType) {
            ResponseType.Success -> (localVarResponse as Success<*>).data as WatchGroup
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
     * POST /syncplay/groups
     * Start watching something together; the caller is the first member.
     * 
     * @param createWatchGroupRequest 
     * @return ApiResponse<WatchGroup?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class)
    fun createWatchGroupWithHttpInfo(createWatchGroupRequest: CreateWatchGroupRequest) : ApiResponse<WatchGroup?> {
        val localVariableConfig = createWatchGroupRequestConfig(createWatchGroupRequest = createWatchGroupRequest)

        return request<CreateWatchGroupRequest, WatchGroup>(
            localVariableConfig
        )
    }

    /**
     * To obtain the request config of the operation createWatchGroup
     *
     * @param createWatchGroupRequest 
     * @return RequestConfig
     */
    fun createWatchGroupRequestConfig(createWatchGroupRequest: CreateWatchGroupRequest) : RequestConfig<CreateWatchGroupRequest> {
        val localVariableBody = createWatchGroupRequest
        val localVariableQuery: MultiValueMap = mutableMapOf()
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        localVariableHeaders["Content-Type"] = "application/json"
        localVariableHeaders["Accept"] = "application/json"

        return RequestConfig(
            method = RequestMethod.POST,
            path = "/syncplay/groups",
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
            body = localVariableBody
        )
    }

    /**
     * GET /syncplay/groups/{groupId}
     * The group&#39;s state. With since, waits (up to 25 s) for a newer version - long polling.
     * 
     * @param groupId 
     * @param since  (optional)
     * @return WatchGroup
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    fun getWatchGroup(groupId: kotlin.String, since: kotlin.Long? = null) : WatchGroup {
        val localVarResponse = getWatchGroupWithHttpInfo(groupId = groupId, since = since)

        return when (localVarResponse.responseType) {
            ResponseType.Success -> (localVarResponse as Success<*>).data as WatchGroup
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
     * GET /syncplay/groups/{groupId}
     * The group&#39;s state. With since, waits (up to 25 s) for a newer version - long polling.
     * 
     * @param groupId 
     * @param since  (optional)
     * @return ApiResponse<WatchGroup?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class)
    fun getWatchGroupWithHttpInfo(groupId: kotlin.String, since: kotlin.Long?) : ApiResponse<WatchGroup?> {
        val localVariableConfig = getWatchGroupRequestConfig(groupId = groupId, since = since)

        return request<Unit, WatchGroup>(
            localVariableConfig
        )
    }

    /**
     * To obtain the request config of the operation getWatchGroup
     *
     * @param groupId 
     * @param since  (optional)
     * @return RequestConfig
     */
    fun getWatchGroupRequestConfig(groupId: kotlin.String, since: kotlin.Long?) : RequestConfig<Unit> {
        val localVariableBody = null
        val localVariableQuery: MultiValueMap = mutableMapOf<kotlin.String, kotlin.collections.List<kotlin.String>>()
            .apply {
                if (since != null) {
                    put("since", listOf(since.toString()))
                }
            }
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        localVariableHeaders["Accept"] = "application/json"

        return RequestConfig(
            method = RequestMethod.GET,
            path = "/syncplay/groups/{groupId}".replace("{"+"groupId"+"}", encodeURIComponent(groupId.toString())),
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
            body = localVariableBody
        )
    }

    /**
     * POST /syncplay/groups/{groupId}/join
     * Join a group.
     * 
     * @param groupId 
     * @return WatchGroup
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    fun joinWatchGroup(groupId: kotlin.String) : WatchGroup {
        val localVarResponse = joinWatchGroupWithHttpInfo(groupId = groupId)

        return when (localVarResponse.responseType) {
            ResponseType.Success -> (localVarResponse as Success<*>).data as WatchGroup
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
     * POST /syncplay/groups/{groupId}/join
     * Join a group.
     * 
     * @param groupId 
     * @return ApiResponse<WatchGroup?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class)
    fun joinWatchGroupWithHttpInfo(groupId: kotlin.String) : ApiResponse<WatchGroup?> {
        val localVariableConfig = joinWatchGroupRequestConfig(groupId = groupId)

        return request<Unit, WatchGroup>(
            localVariableConfig
        )
    }

    /**
     * To obtain the request config of the operation joinWatchGroup
     *
     * @param groupId 
     * @return RequestConfig
     */
    fun joinWatchGroupRequestConfig(groupId: kotlin.String) : RequestConfig<Unit> {
        val localVariableBody = null
        val localVariableQuery: MultiValueMap = mutableMapOf()
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        localVariableHeaders["Accept"] = "application/json"

        return RequestConfig(
            method = RequestMethod.POST,
            path = "/syncplay/groups/{groupId}/join".replace("{"+"groupId"+"}", encodeURIComponent(groupId.toString())),
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
            body = localVariableBody
        )
    }

    /**
     * POST /syncplay/groups/{groupId}/leave
     * Leave a group; the last one out ends it.
     * 
     * @param groupId 
     * @return void
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    fun leaveWatchGroup(groupId: kotlin.String) : Unit {
        val localVarResponse = leaveWatchGroupWithHttpInfo(groupId = groupId)

        return when (localVarResponse.responseType) {
            ResponseType.Success -> Unit
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
     * POST /syncplay/groups/{groupId}/leave
     * Leave a group; the last one out ends it.
     * 
     * @param groupId 
     * @return ApiResponse<Unit?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Throws(IllegalStateException::class, IOException::class)
    fun leaveWatchGroupWithHttpInfo(groupId: kotlin.String) : ApiResponse<Unit?> {
        val localVariableConfig = leaveWatchGroupRequestConfig(groupId = groupId)

        return request<Unit, Unit>(
            localVariableConfig
        )
    }

    /**
     * To obtain the request config of the operation leaveWatchGroup
     *
     * @param groupId 
     * @return RequestConfig
     */
    fun leaveWatchGroupRequestConfig(groupId: kotlin.String) : RequestConfig<Unit> {
        val localVariableBody = null
        val localVariableQuery: MultiValueMap = mutableMapOf()
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        localVariableHeaders["Accept"] = "application/json"

        return RequestConfig(
            method = RequestMethod.POST,
            path = "/syncplay/groups/{groupId}/leave".replace("{"+"groupId"+"}", encodeURIComponent(groupId.toString())),
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
            body = localVariableBody
        )
    }

    /**
     * GET /syncplay/groups
     * Watch-together groups the caller can join (members can see any group on the server).
     * 
     * @return kotlin.collections.List<WatchGroup>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    fun listWatchGroups() : kotlin.collections.List<WatchGroup> {
        val localVarResponse = listWatchGroupsWithHttpInfo()

        return when (localVarResponse.responseType) {
            ResponseType.Success -> (localVarResponse as Success<*>).data as kotlin.collections.List<WatchGroup>
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
     * GET /syncplay/groups
     * Watch-together groups the caller can join (members can see any group on the server).
     * 
     * @return ApiResponse<kotlin.collections.List<WatchGroup>?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class)
    fun listWatchGroupsWithHttpInfo() : ApiResponse<kotlin.collections.List<WatchGroup>?> {
        val localVariableConfig = listWatchGroupsRequestConfig()

        return request<Unit, kotlin.collections.List<WatchGroup>>(
            localVariableConfig
        )
    }

    /**
     * To obtain the request config of the operation listWatchGroups
     *
     * @return RequestConfig
     */
    fun listWatchGroupsRequestConfig() : RequestConfig<Unit> {
        val localVariableBody = null
        val localVariableQuery: MultiValueMap = mutableMapOf()
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        localVariableHeaders["Accept"] = "application/json"

        return RequestConfig(
            method = RequestMethod.GET,
            path = "/syncplay/groups",
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
            body = localVariableBody
        )
    }

    /**
     * POST /syncplay/groups/{groupId}/command
     * Play, pause or seek for everyone in the group (members only).
     * 
     * @param groupId 
     * @param watchGroupCommandRequest 
     * @return WatchGroup
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    fun watchGroupCommand(groupId: kotlin.String, watchGroupCommandRequest: WatchGroupCommandRequest) : WatchGroup {
        val localVarResponse = watchGroupCommandWithHttpInfo(groupId = groupId, watchGroupCommandRequest = watchGroupCommandRequest)

        return when (localVarResponse.responseType) {
            ResponseType.Success -> (localVarResponse as Success<*>).data as WatchGroup
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
     * POST /syncplay/groups/{groupId}/command
     * Play, pause or seek for everyone in the group (members only).
     * 
     * @param groupId 
     * @param watchGroupCommandRequest 
     * @return ApiResponse<WatchGroup?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class)
    fun watchGroupCommandWithHttpInfo(groupId: kotlin.String, watchGroupCommandRequest: WatchGroupCommandRequest) : ApiResponse<WatchGroup?> {
        val localVariableConfig = watchGroupCommandRequestConfig(groupId = groupId, watchGroupCommandRequest = watchGroupCommandRequest)

        return request<WatchGroupCommandRequest, WatchGroup>(
            localVariableConfig
        )
    }

    /**
     * To obtain the request config of the operation watchGroupCommand
     *
     * @param groupId 
     * @param watchGroupCommandRequest 
     * @return RequestConfig
     */
    fun watchGroupCommandRequestConfig(groupId: kotlin.String, watchGroupCommandRequest: WatchGroupCommandRequest) : RequestConfig<WatchGroupCommandRequest> {
        val localVariableBody = watchGroupCommandRequest
        val localVariableQuery: MultiValueMap = mutableMapOf()
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        localVariableHeaders["Content-Type"] = "application/json"
        localVariableHeaders["Accept"] = "application/json"

        return RequestConfig(
            method = RequestMethod.POST,
            path = "/syncplay/groups/{groupId}/command".replace("{"+"groupId"+"}", encodeURIComponent(groupId.toString())),
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
            body = localVariableBody
        )
    }


    private fun encodeURIComponent(uriComponent: kotlin.String): kotlin.String =
        HttpUrl.Builder().scheme("http").host("localhost").addPathSegment(uriComponent).build().encodedPathSegments[0]
}
