/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package app.marquee.api.models

import app.marquee.api.models.ActivityTask

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param serverVersion Lets clients notice a server upgrade and reload.
 * @param tasks 
 */
@Serializable

data class Activity (

    /* Lets clients notice a server upgrade and reload. */
    @SerialName(value = "serverVersion")
    val serverVersion: kotlin.String,

    @SerialName(value = "tasks")
    val tasks: kotlin.collections.List<ActivityTask>

) {


}

