/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package app.marquee.api.models


import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param provider 
 * @param subtitle 
 * @param hi 
 * @param forced 
 * @param originalFormat 
 */
@Serializable

data class BazarrPick (

    @SerialName(value = "provider")
    val provider: kotlin.String,

    @SerialName(value = "subtitle")
    val subtitle: kotlin.String,

    @SerialName(value = "hi")
    val hi: kotlin.Boolean? = null,

    @SerialName(value = "forced")
    val forced: kotlin.Boolean? = null,

    @SerialName(value = "originalFormat")
    val originalFormat: kotlin.Boolean? = null

) {


}

