/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package app.marquee.api.models


import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param provider 
 * @param subtitle Bazarr's opaque handle for this result; send it back to download it.
 * @param language 
 * @param score Bazarr's match score (higher is better; hash matches are best).
 * @param release The release names it was made for.
 * @param hi 
 * @param forced 
 * @param uploader 
 * @param originalFormat 
 */
@Serializable

data class BazarrCandidate (

    @SerialName(value = "provider")
    val provider: kotlin.String,

    /* Bazarr's opaque handle for this result; send it back to download it. */
    @SerialName(value = "subtitle")
    val subtitle: kotlin.String,

    @SerialName(value = "language")
    val language: kotlin.String,

    /* Bazarr's match score (higher is better; hash matches are best). */
    @SerialName(value = "score")
    val score: kotlin.Int,

    /* The release names it was made for. */
    @SerialName(value = "release")
    val release: kotlin.String? = null,

    @SerialName(value = "hi")
    val hi: kotlin.Boolean? = null,

    @SerialName(value = "forced")
    val forced: kotlin.Boolean? = null,

    @SerialName(value = "uploader")
    val uploader: kotlin.String? = null,

    @SerialName(value = "originalFormat")
    val originalFormat: kotlin.Boolean? = null

) {


}

