/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package app.marquee.api.models


import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param itemId 
 * @param quality high 1080p, medium 720p, low 480p (HEVC MP4).
 * @param fileId A specific version; default is the best.
 */
@Serializable

data class CreateDownloadRequest (

    @SerialName(value = "itemId")
    val itemId: kotlin.Long,

    /* high 1080p, medium 720p, low 480p (HEVC MP4). */
    @SerialName(value = "quality")
    val quality: CreateDownloadRequest.Quality,

    /* A specific version; default is the best. */
    @SerialName(value = "fileId")
    val fileId: kotlin.Long? = null

) {

    /**
     * high 1080p, medium 720p, low 480p (HEVC MP4).
     *
     * Values: ORIGINAL,HIGH,MEDIUM,LOW
     */
    @Serializable
    enum class Quality(val value: kotlin.String) {
        @SerialName(value = "original") ORIGINAL("original"),
        @SerialName(value = "high") HIGH("high"),
        @SerialName(value = "medium") MEDIUM("medium"),
        @SerialName(value = "low") LOW("low");
    }

}

