/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package app.marquee.api.models


import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param personId 
 * @param name 
 * @param role 
 * @param character 
 * @param hasPhoto 
 */
@Serializable

data class Credit (

    @SerialName(value = "personId")
    val personId: kotlin.Long,

    @SerialName(value = "name")
    val name: kotlin.String,

    @SerialName(value = "role")
    val role: Credit.Role,

    @SerialName(value = "character")
    val character: kotlin.String? = null,

    @SerialName(value = "hasPhoto")
    val hasPhoto: kotlin.Boolean? = null

) {

    /**
     * 
     *
     * Values: ACTOR,DIRECTOR,WRITER,CREATOR,PRODUCER,COMPOSER
     */
    @Serializable
    enum class Role(val value: kotlin.String) {
        @SerialName(value = "actor") ACTOR("actor"),
        @SerialName(value = "director") DIRECTOR("director"),
        @SerialName(value = "writer") WRITER("writer"),
        @SerialName(value = "creator") CREATOR("creator"),
        @SerialName(value = "producer") PRODUCER("producer"),
        @SerialName(value = "composer") COMPOSER("composer");
    }

}

