/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package app.marquee.api.models


import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param id 
 * @param userId 
 * @param userName 
 * @param name 
 * @param platform 
 * @param lastSeenAt 
 * @param createdAt 
 * @param current This is the device making the request.
 * @param product 
 * @param version 
 * @param lastIp 
 */
@Serializable

data class Device (

    @SerialName(value = "id")
    val id: kotlin.Long,

    @SerialName(value = "userId")
    val userId: kotlin.Long,

    @SerialName(value = "userName")
    val userName: kotlin.String,

    @SerialName(value = "name")
    val name: kotlin.String,

    @SerialName(value = "platform")
    val platform: kotlin.String,

    @Contextual @SerialName(value = "lastSeenAt")
    val lastSeenAt: java.time.OffsetDateTime,

    @Contextual @SerialName(value = "createdAt")
    val createdAt: java.time.OffsetDateTime,

    /* This is the device making the request. */
    @SerialName(value = "current")
    val current: kotlin.Boolean,

    @SerialName(value = "product")
    val product: kotlin.String? = null,

    @SerialName(value = "version")
    val version: kotlin.String? = null,

    @SerialName(value = "lastIp")
    val lastIp: kotlin.String? = null

) {


}

