/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package app.marquee.api.models

import app.marquee.api.models.DirectoryEntry

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param propertyEntries 
 * @param path Null when listing the browse roots.
 * @param parent Null at a browse root.
 */
@Serializable

data class DirectoryListing (

    @SerialName(value = "entries")
    val propertyEntries: kotlin.collections.List<DirectoryEntry>,

    /* Null when listing the browse roots. */
    @SerialName(value = "path")
    val path: kotlin.String? = null,

    /* Null at a browse root. */
    @SerialName(value = "parent")
    val parent: kotlin.String? = null

) {


}

