/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package app.marquee.api.models


import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param streamId 
 * @param remaining Downloads OpenSubtitles allows today.
 */
@Serializable

data class DownloadSubtitle201Response (

    @SerialName(value = "streamId")
    val streamId: kotlin.Long,

    /* Downloads OpenSubtitles allows today. */
    @SerialName(value = "remaining")
    val remaining: kotlin.Int? = null

) {


}

