/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package app.marquee.api.models


import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param fileId The result's OpenSubtitles file id.
 * @param language 
 * @param release 
 * @param hearingImpaired 
 */
@Serializable

data class DownloadSubtitleRequest (

    /* The result's OpenSubtitles file id. */
    @SerialName(value = "fileId")
    val fileId: kotlin.Long,

    @SerialName(value = "language")
    val language: kotlin.String,

    @SerialName(value = "release")
    val release: kotlin.String? = null,

    @SerialName(value = "hearingImpaired")
    val hearingImpaired: kotlin.Boolean? = null

) {


}

