/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package app.marquee.api.models


import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param id \"original-<item>\" for originals.
 * @param itemId 
 * @param quality 
 * @param status 
 * @param progress Conversion progress, 0–1.
 * @param propertySize Bytes, once ready.
 * @param url Where to fetch the file once ready (supports HTTP ranges; send the token as for streams).
 * @param fileName 
 * @param error 
 * @param createdAt 
 */
@Serializable

data class Download (

    /* \"original-<item>\" for originals. */
    @SerialName(value = "id")
    val id: kotlin.String,

    @SerialName(value = "itemId")
    val itemId: kotlin.Long,

    @SerialName(value = "quality")
    val quality: Download.Quality,

    @SerialName(value = "status")
    val status: Download.Status,

    /* Conversion progress, 0–1. */
    @Contextual @SerialName(value = "progress")
    val progress: java.math.BigDecimal,

    /* Bytes, once ready. */
    @SerialName(value = "size")
    val propertySize: kotlin.Long? = null,

    /* Where to fetch the file once ready (supports HTTP ranges; send the token as for streams). */
    @SerialName(value = "url")
    val url: kotlin.String? = null,

    @SerialName(value = "fileName")
    val fileName: kotlin.String? = null,

    @SerialName(value = "error")
    val error: kotlin.String? = null,

    @Contextual @SerialName(value = "createdAt")
    val createdAt: java.time.OffsetDateTime? = null

) {

    /**
     * 
     *
     * Values: ORIGINAL,HIGH,MEDIUM,LOW
     */
    @Serializable
    enum class Quality(val value: kotlin.String) {
        @SerialName(value = "original") ORIGINAL("original"),
        @SerialName(value = "high") HIGH("high"),
        @SerialName(value = "medium") MEDIUM("medium"),
        @SerialName(value = "low") LOW("low");
    }
    /**
     * 
     *
     * Values: QUEUED,CONVERTING,READY,FAILED
     */
    @Serializable
    enum class Status(val value: kotlin.String) {
        @SerialName(value = "queued") QUEUED("queued"),
        @SerialName(value = "converting") CONVERTING("converting"),
        @SerialName(value = "ready") READY("ready"),
        @SerialName(value = "failed") FAILED("failed");
    }

}

