/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package app.marquee.api.models

import app.marquee.api.models.ItemSummary

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param item 
 * @param detail 
 * @param fileId 
 * @param path 
 * @param related duplicates: the other copies.
 */
@Serializable

data class HealthIssue (

    @SerialName(value = "item")
    val item: ItemSummary,

    @SerialName(value = "detail")
    val detail: kotlin.String,

    @SerialName(value = "fileId")
    val fileId: kotlin.Long? = null,

    @SerialName(value = "path")
    val path: kotlin.String? = null,

    /* duplicates: the other copies. */
    @SerialName(value = "related")
    val related: kotlin.collections.List<ItemSummary>? = null

) {


}

