/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package app.marquee.api.models


import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param id 
 * @param title 
 * @param startedAt 
 * @param source 
 * @param userName 
 * @param deviceName 
 * @param itemId 
 * @param stoppedAt 
 * @param positionMs 
 * @param method 
 * @param networkClass 
 * @param encoder 
 * @param bitrateKbps 
 */
@Serializable

data class HistoryEntry (

    @SerialName(value = "id")
    val id: kotlin.Long,

    @SerialName(value = "title")
    val title: kotlin.String,

    @Contextual @SerialName(value = "startedAt")
    val startedAt: java.time.OffsetDateTime,

    @SerialName(value = "source")
    val source: HistoryEntry.Source,

    @SerialName(value = "userName")
    val userName: kotlin.String? = null,

    @SerialName(value = "deviceName")
    val deviceName: kotlin.String? = null,

    @SerialName(value = "itemId")
    val itemId: kotlin.Long? = null,

    @Contextual @SerialName(value = "stoppedAt")
    val stoppedAt: java.time.OffsetDateTime? = null,

    @SerialName(value = "positionMs")
    val positionMs: kotlin.Long? = null,

    @SerialName(value = "method")
    val method: kotlin.String? = null,

    @SerialName(value = "networkClass")
    val networkClass: kotlin.String? = null,

    @SerialName(value = "encoder")
    val encoder: kotlin.String? = null,

    @SerialName(value = "bitrateKbps")
    val bitrateKbps: kotlin.Int? = null

) {

    /**
     * 
     *
     * Values: MARQUEE,PLEX
     */
    @Serializable
    enum class Source(val value: kotlin.String) {
        @SerialName(value = "marquee") MARQUEE("marquee"),
        @SerialName(value = "plex") PLEX("plex");
    }

}

