/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package app.marquee.api.models


import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param id 
 * @param title Filled in by the server.
 * @param hidden 
 * @param pinned A pinned collection or playlist (remove it from the list to unpin).
 */
@Serializable

data class HomeLayoutRow (

    @SerialName(value = "id")
    val id: kotlin.String,

    /* Filled in by the server. */
    @SerialName(value = "title")
    val title: kotlin.String? = null,

    @SerialName(value = "hidden")
    val hidden: kotlin.Boolean? = null,

    /* A pinned collection or playlist (remove it from the list to unpin). */
    @SerialName(value = "pinned")
    val pinned: kotlin.Boolean? = null

) {


}

