/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package app.marquee.api.models

import app.marquee.api.models.LiveTvSource

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param seerrUrl Seerr's address, e.g. http://10.1.1.10:5055. Empty turns requests off.
 * @param seerrApiKeySet 
 * @param lastFmConfigured Last.fm's API key and shared secret are set, so people can connect Last.fm (MUSIC-12).
 * @param dvrPaddingBefore Minutes recordings start early.
 * @param dvrPaddingAfter Minutes recordings run late.
 * @param liveTvSources 
 */
@Serializable

data class IntegrationSettings (

    /* Seerr's address, e.g. http://10.1.1.10:5055. Empty turns requests off. */
    @SerialName(value = "seerrUrl")
    val seerrUrl: kotlin.String? = null,

    @SerialName(value = "seerrApiKeySet")
    val seerrApiKeySet: kotlin.Boolean? = null,

    /* Last.fm's API key and shared secret are set, so people can connect Last.fm (MUSIC-12). */
    @SerialName(value = "lastFmConfigured")
    val lastFmConfigured: kotlin.Boolean? = null,

    /* Minutes recordings start early. */
    @SerialName(value = "dvrPaddingBefore")
    val dvrPaddingBefore: kotlin.Int? = null,

    /* Minutes recordings run late. */
    @SerialName(value = "dvrPaddingAfter")
    val dvrPaddingAfter: kotlin.Int? = null,

    @SerialName(value = "liveTvSources")
    val liveTvSources: kotlin.collections.List<LiveTvSource>? = null

) {


}

