/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package app.marquee.api.models

import app.marquee.api.models.UserRestrictions

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param note 
 * @param expiresDays Default 7.
 * @param restrictions 
 */
@Serializable

data class InviteCreate (

    @SerialName(value = "note")
    val note: kotlin.String? = null,

    /* Default 7. */
    @SerialName(value = "expiresDays")
    val expiresDays: kotlin.Int? = null,

    @SerialName(value = "restrictions")
    val restrictions: UserRestrictions? = null

) {


}

