/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package app.marquee.api.models

import app.marquee.api.models.UserRestrictions

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param id 
 * @param createdAt 
 * @param restrictions 
 * @param note Who it's for, e.g. Mum.
 * @param expiresAt 
 * @param usedAt 
 * @param usedBy The display name of who joined with it.
 */
@Serializable

data class Invite (

    @SerialName(value = "id")
    val id: kotlin.Long,

    @Contextual @SerialName(value = "createdAt")
    val createdAt: java.time.OffsetDateTime,

    @SerialName(value = "restrictions")
    val restrictions: UserRestrictions,

    /* Who it's for, e.g. Mum. */
    @SerialName(value = "note")
    val note: kotlin.String? = null,

    @Contextual @SerialName(value = "expiresAt")
    val expiresAt: java.time.OffsetDateTime? = null,

    @Contextual @SerialName(value = "usedAt")
    val usedAt: java.time.OffsetDateTime? = null,

    /* The display name of who joined with it. */
    @SerialName(value = "usedBy")
    val usedBy: kotlin.String? = null

) {


}

