/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package app.marquee.api.models

import app.marquee.api.models.Invite

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param invite 
 * @param token Shown once.
 * @param path The web page to send, relative to the server's address: /join/<token>.
 */
@Serializable

data class InviteCreated (

    @SerialName(value = "invite")
    val invite: Invite,

    /* Shown once. */
    @SerialName(value = "token")
    val token: kotlin.String,

    /* The web page to send, relative to the server's address: /join/<token>. */
    @SerialName(value = "path")
    val path: kotlin.String

) {


}

