/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package app.marquee.api.models

import app.marquee.api.models.MediaFile

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param itemId 
 * @param itemTitle 
 * @param file 
 * @param addedAt 
 * @param versionLabel 
 */
@Serializable

data class IssueFile (

    @SerialName(value = "itemId")
    val itemId: kotlin.Long,

    @SerialName(value = "itemTitle")
    val itemTitle: kotlin.String,

    @SerialName(value = "file")
    val file: MediaFile,

    @Contextual @SerialName(value = "addedAt")
    val addedAt: java.time.OffsetDateTime,

    @SerialName(value = "versionLabel")
    val versionLabel: kotlin.String? = null

) {


}

