/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package app.marquee.api.models


import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * Artwork ids for /images/{artworkId}. Seasons and episodes fall back to the show's art, tracks to the album's.
 *
 * @param poster 
 * @param backdrop 
 * @param thumb 
 * @param logo 
 */
@Serializable

data class ItemImages (

    @SerialName(value = "poster")
    val poster: kotlin.Long? = null,

    @SerialName(value = "backdrop")
    val backdrop: kotlin.Long? = null,

    @SerialName(value = "thumb")
    val thumb: kotlin.Long? = null,

    @SerialName(value = "logo")
    val logo: kotlin.Long? = null

) {


}

