/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package app.marquee.api.models

import app.marquee.api.models.Review

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param count Number of ratings.
 * @param reviews Everyone who rated or commented, people with comments first, newest first.
 * @param average Community average (absent when nobody rated it).
 */
@Serializable

data class ItemReviews (

    /* Number of ratings. */
    @SerialName(value = "count")
    val count: kotlin.Int,

    /* Everyone who rated or commented, people with comments first, newest first. */
    @SerialName(value = "reviews")
    val reviews: kotlin.collections.List<Review>,

    /* Community average (absent when nobody rated it). */
    @SerialName(value = "average")
    val average: kotlin.Double? = null

) {


}

