/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package app.marquee.api.models


import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param language 
 * @param episodeOrdering TV/anime only.
 * @param ignorePatterns 
 * @param includeInHome 
 * @param includeInSearch 
 * @param scanIntervalHours 0 = rely on file watching only.
 */
@Serializable

data class LibraryOptions (

    @SerialName(value = "language")
    val language: kotlin.String? = null,

    /* TV/anime only. */
    @SerialName(value = "episodeOrdering")
    val episodeOrdering: LibraryOptions.EpisodeOrdering? = null,

    @SerialName(value = "ignorePatterns")
    val ignorePatterns: kotlin.collections.List<kotlin.String>? = null,

    @SerialName(value = "includeInHome")
    val includeInHome: kotlin.Boolean? = null,

    @SerialName(value = "includeInSearch")
    val includeInSearch: kotlin.Boolean? = null,

    /* 0 = rely on file watching only. */
    @SerialName(value = "scanIntervalHours")
    val scanIntervalHours: kotlin.Int? = null

) {

    /**
     * TV/anime only.
     *
     * Values: AIRED,ABSOLUTE,DVD
     */
    @Serializable
    enum class EpisodeOrdering(val value: kotlin.String) {
        @SerialName(value = "aired") AIRED("aired"),
        @SerialName(value = "absolute") ABSOLUTE("absolute"),
        @SerialName(value = "dvd") DVD("dvd");
    }

}

