/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package app.marquee.api.models

import app.marquee.api.models.LibraryOptions
import app.marquee.api.models.LibraryType
import app.marquee.api.models.ScanProgress

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param id 
 * @param name 
 * @param type 
 * @param paths 
 * @param options 
 * @param itemCount 
 * @param scanStatus 
 * @param createdAt 
 * @param updatedAt 
 * @param scanProgress 
 * @param lastScanResult Summary of the last scan, e.g. 6596 files: 12 added…
 * @param lastScanError 
 * @param lastScannedAt 
 */
@Serializable

data class Library (

    @SerialName(value = "id")
    val id: kotlin.Long,

    @SerialName(value = "name")
    val name: kotlin.String,

    @Contextual @SerialName(value = "type")
    val type: LibraryType,

    @SerialName(value = "paths")
    val paths: kotlin.collections.List<kotlin.String>,

    @SerialName(value = "options")
    val options: LibraryOptions,

    @SerialName(value = "itemCount")
    val itemCount: kotlin.Int,

    @SerialName(value = "scanStatus")
    val scanStatus: Library.ScanStatus,

    @Contextual @SerialName(value = "createdAt")
    val createdAt: java.time.OffsetDateTime,

    @Contextual @SerialName(value = "updatedAt")
    val updatedAt: java.time.OffsetDateTime,

    @SerialName(value = "scanProgress")
    val scanProgress: ScanProgress? = null,

    /* Summary of the last scan, e.g. 6596 files: 12 added… */
    @SerialName(value = "lastScanResult")
    val lastScanResult: kotlin.String? = null,

    @SerialName(value = "lastScanError")
    val lastScanError: kotlin.String? = null,

    @Contextual @SerialName(value = "lastScannedAt")
    val lastScannedAt: java.time.OffsetDateTime? = null

) {

    /**
     * 
     *
     * Values: IDLE,QUEUED,SCANNING
     */
    @Serializable
    enum class ScanStatus(val value: kotlin.String) {
        @SerialName(value = "idle") IDLE("idle"),
        @SerialName(value = "queued") QUEUED("queued"),
        @SerialName(value = "scanning") SCANNING("scanning");
    }

}

