/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package app.marquee.api.models

import app.marquee.api.models.ItemSummary
import app.marquee.api.models.ListeningRecapTopDay
import app.marquee.api.models.ListeningRecapTopGenresInner
import app.marquee.api.models.RecapEntry

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * A person's year in music (MUSIC-22), from their play history.
 *
 * @param year 
 * @param minutes 
 * @param plays 
 * @param tracks Different tracks played.
 * @param artists Different artists played.
 * @param newArtists Artists first played this year.
 * @param topArtists 
 * @param topAlbums 
 * @param topTracks 
 * @param topGenres 
 * @param byMonth Minutes listened in each month, January first.
 * @param byHour Plays started in each hour of the day (server time), 0–23.
 * @param longestStreakDays Most days in a row with music.
 * @param topDay 
 * @param firstTrack 
 * @param videoHours Hours of movies and TV watched the same year.
 */
@Serializable

data class ListeningRecap (

    @SerialName(value = "year")
    val year: kotlin.Int,

    @SerialName(value = "minutes")
    val minutes: kotlin.Int,

    @SerialName(value = "plays")
    val plays: kotlin.Int,

    /* Different tracks played. */
    @SerialName(value = "tracks")
    val tracks: kotlin.Int,

    /* Different artists played. */
    @SerialName(value = "artists")
    val artists: kotlin.Int,

    /* Artists first played this year. */
    @SerialName(value = "newArtists")
    val newArtists: kotlin.Int,

    @SerialName(value = "topArtists")
    val topArtists: kotlin.collections.List<RecapEntry>,

    @SerialName(value = "topAlbums")
    val topAlbums: kotlin.collections.List<RecapEntry>,

    @SerialName(value = "topTracks")
    val topTracks: kotlin.collections.List<RecapEntry>,

    @SerialName(value = "topGenres")
    val topGenres: kotlin.collections.List<ListeningRecapTopGenresInner>,

    /* Minutes listened in each month, January first. */
    @SerialName(value = "byMonth")
    val byMonth: kotlin.collections.List<kotlin.Int>,

    /* Plays started in each hour of the day (server time), 0–23. */
    @SerialName(value = "byHour")
    val byHour: kotlin.collections.List<kotlin.Int>,

    /* Most days in a row with music. */
    @SerialName(value = "longestStreakDays")
    val longestStreakDays: kotlin.Int,

    @SerialName(value = "topDay")
    val topDay: ListeningRecapTopDay? = null,

    @SerialName(value = "firstTrack")
    val firstTrack: ItemSummary? = null,

    /* Hours of movies and TV watched the same year. */
    @SerialName(value = "videoHours")
    val videoHours: kotlin.Double? = null

) {


}

