/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package app.marquee.api.models


import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param id 
 * @param start 
 * @param end 
 * @param title 
 * @param subtitle The episode's name.
 * @param description 
 * @param category 
 * @param episode As the guide gives it, e.g. S2 E5.
 * @param imageUrl 
 */
@Serializable

data class LiveProgramme (

    @SerialName(value = "id")
    val id: kotlin.Long,

    @Contextual @SerialName(value = "start")
    val start: java.time.OffsetDateTime,

    @Contextual @SerialName(value = "end")
    val end: java.time.OffsetDateTime,

    @SerialName(value = "title")
    val title: kotlin.String,

    /* The episode's name. */
    @SerialName(value = "subtitle")
    val subtitle: kotlin.String? = null,

    @SerialName(value = "description")
    val description: kotlin.String? = null,

    @SerialName(value = "category")
    val category: kotlin.String? = null,

    /* As the guide gives it, e.g. S2 E5. */
    @SerialName(value = "episode")
    val episode: kotlin.String? = null,

    @SerialName(value = "imageUrl")
    val imageUrl: kotlin.String? = null

) {


}

