/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package app.marquee.api.models


import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param id 
 * @param name 
 * @param channels 
 * @param programmes 
 * @param refreshedAt 
 * @param error 
 */
@Serializable

data class LiveTvStatusSourcesInner (

    @SerialName(value = "id")
    val id: kotlin.String,

    @SerialName(value = "name")
    val name: kotlin.String,

    @SerialName(value = "channels")
    val channels: kotlin.Int,

    @SerialName(value = "programmes")
    val programmes: kotlin.Int,

    @Contextual @SerialName(value = "refreshedAt")
    val refreshedAt: java.time.OffsetDateTime? = null,

    @SerialName(value = "error")
    val error: kotlin.String? = null

) {


}

