/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package app.marquee.api.models

import app.marquee.api.models.LiveProgramme

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param id 
 * @param name 
 * @param favorite 
 * @param number The channel number as the source gives it (e.g. 4 or 4.1).
 * @param group 
 * @param logoUrl Server-relative; no token needed.
 * @param now 
 * @param next 
 */
@Serializable

data class LiveChannel (

    @SerialName(value = "id")
    val id: kotlin.Long,

    @SerialName(value = "name")
    val name: kotlin.String,

    @SerialName(value = "favorite")
    val favorite: kotlin.Boolean,

    /* The channel number as the source gives it (e.g. 4 or 4.1). */
    @SerialName(value = "number")
    val number: kotlin.String? = null,

    @SerialName(value = "group")
    val group: kotlin.String? = null,

    /* Server-relative; no token needed. */
    @SerialName(value = "logoUrl")
    val logoUrl: kotlin.String? = null,

    @SerialName(value = "now")
    val now: LiveProgramme? = null,

    @SerialName(value = "next")
    val next: LiveProgramme? = null

) {


}

