/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package app.marquee.api.models


import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param time 
 * @param level 
 * @param message 
 * @param attrs 
 */
@Serializable

data class LogEntry (

    @Contextual @SerialName(value = "time")
    val time: java.time.OffsetDateTime,

    @SerialName(value = "level")
    val level: LogEntry.Level,

    @SerialName(value = "message")
    val message: kotlin.String,

    @SerialName(value = "attrs")
    val attrs: kotlin.collections.Map<kotlin.String, kotlin.String>? = null

) {

    /**
     * 
     *
     * Values: DEBUG,INFO,WARN,ERROR
     */
    @Serializable
    enum class Level(val value: kotlin.String) {
        @SerialName(value = "debug") DEBUG("debug"),
        @SerialName(value = "info") INFO("info"),
        @SerialName(value = "warn") WARN("warn"),
        @SerialName(value = "error") ERROR("error");
    }

}

