/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package app.marquee.api.models

import app.marquee.api.models.LyricLine

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param synced 
 * @param source 
 * @param lines 
 */
@Serializable

data class Lyrics (

    @SerialName(value = "synced")
    val synced: kotlin.Boolean,

    @SerialName(value = "source")
    val source: Lyrics.Source,

    @SerialName(value = "lines")
    val lines: kotlin.collections.List<LyricLine>

) {

    /**
     * 
     *
     * Values: EMBEDDED,SIDECAR,LRCLIB
     */
    @Serializable
    enum class Source(val value: kotlin.String) {
        @SerialName(value = "embedded") EMBEDDED("embedded"),
        @SerialName(value = "sidecar") SIDECAR("sidecar"),
        @SerialName(value = "lrclib") LRCLIB("lrclib");
    }

}

