/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package app.marquee.api.models


import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param tmdbId 
 * @param mediaType 
 * @param seasons Shows only; absent or empty = every season not already here.
 */
@Serializable

data class MediaRequestCreate (

    @SerialName(value = "tmdbId")
    val tmdbId: kotlin.Long,

    @SerialName(value = "mediaType")
    val mediaType: MediaRequestCreate.MediaType,

    /* Shows only; absent or empty = every season not already here. */
    @SerialName(value = "seasons")
    val seasons: kotlin.collections.List<kotlin.Int>? = null

) {

    /**
     * 
     *
     * Values: MOVIE,TV
     */
    @Serializable
    enum class MediaType(val value: kotlin.String) {
        @SerialName(value = "movie") MOVIE("movie"),
        @SerialName(value = "tv") TV("tv");
    }

}

