/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package app.marquee.api.models


import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * Secret keys are write-only. Send an empty string to clear one.
 *
 * @param tmdbApiKey 
 * @param fanartApiKey 
 * @param openSubtitlesApiKey 
 * @param openSubtitlesUsername 
 * @param openSubtitlesPassword 
 * @param omdbApiKey 
 * @param omdbDailyLimit 
 * @param animeEpisodeOrdering 
 */
@Serializable

data class MetadataSettingsUpdate (

    @SerialName(value = "tmdbApiKey")
    val tmdbApiKey: kotlin.String? = null,

    @SerialName(value = "fanartApiKey")
    val fanartApiKey: kotlin.String? = null,

    @SerialName(value = "openSubtitlesApiKey")
    val openSubtitlesApiKey: kotlin.String? = null,

    @SerialName(value = "openSubtitlesUsername")
    val openSubtitlesUsername: kotlin.String? = null,

    @SerialName(value = "openSubtitlesPassword")
    val openSubtitlesPassword: kotlin.String? = null,

    @SerialName(value = "omdbApiKey")
    val omdbApiKey: kotlin.String? = null,

    @SerialName(value = "omdbDailyLimit")
    val omdbDailyLimit: kotlin.Int? = null,

    @SerialName(value = "animeEpisodeOrdering")
    val animeEpisodeOrdering: MetadataSettingsUpdate.AnimeEpisodeOrdering? = null

) {

    /**
     * 
     *
     * Values: SEASONAL,ABSOLUTE
     */
    @Serializable
    enum class AnimeEpisodeOrdering(val value: kotlin.String) {
        @SerialName(value = "seasonal") SEASONAL("seasonal"),
        @SerialName(value = "absolute") ABSOLUTE("absolute");
    }

}

