/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package app.marquee.api.models

import app.marquee.api.models.ItemSummary

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param items 
 * @param understood How the prompt was read, e.g. \"Movies · 1990s · Science Fiction · like 'time travel'\".
 * @param analysed Share of the library ready for Muse (0–1); below 1 while it's still being indexed.
 */
@Serializable

data class MuseVideoResult (

    @SerialName(value = "items")
    val items: kotlin.collections.List<ItemSummary>,

    /* How the prompt was read, e.g. \"Movies · 1990s · Science Fiction · like 'time travel'\". */
    @SerialName(value = "understood")
    val understood: kotlin.String,

    /* Share of the library ready for Muse (0–1); below 1 while it's still being indexed. */
    @SerialName(value = "analysed")
    val analysed: kotlin.Double? = null

) {


}

