/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package app.marquee.api.models


import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param trackId 
 * @param mode 
 * @param exclude Tracks already queued.
 */
@Serializable

data class MusicDJRequest (

    @SerialName(value = "trackId")
    val trackId: kotlin.Long,

    @SerialName(value = "mode")
    val mode: MusicDJRequest.Mode,

    /* Tracks already queued. */
    @SerialName(value = "exclude")
    val exclude: kotlin.collections.List<kotlin.Long>? = null

) {

    /**
     * 
     *
     * Values: WANDER,SUPERFAN,DEEP_CUTS,SAME_ERA
     */
    @Serializable
    enum class Mode(val value: kotlin.String) {
        @SerialName(value = "wander") WANDER("wander"),
        @SerialName(value = "superfan") SUPERFAN("superfan"),
        @SerialName(value = "deep_cuts") DEEP_CUTS("deep_cuts"),
        @SerialName(value = "same_era") SAME_ERA("same_era");
    }

}

