/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package app.marquee.api.models


import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param enabled 
 * @param available The analysis service is running.
 * @param running 
 * @param analyzed 
 * @param total 
 * @param model 
 * @param device 
 * @param failed 
 * @param progress 
 * @param runTotal 
 */
@Serializable

data class MusicStatus (

    @SerialName(value = "enabled")
    val enabled: kotlin.Boolean,

    /* The analysis service is running. */
    @SerialName(value = "available")
    val available: kotlin.Boolean,

    @SerialName(value = "running")
    val running: kotlin.Boolean,

    @SerialName(value = "analyzed")
    val analyzed: kotlin.Int,

    @SerialName(value = "total")
    val total: kotlin.Int,

    @SerialName(value = "model")
    val model: kotlin.String? = null,

    @SerialName(value = "device")
    val device: kotlin.String? = null,

    @SerialName(value = "failed")
    val failed: kotlin.Int? = null,

    @SerialName(value = "progress")
    val progress: kotlin.Int? = null,

    @SerialName(value = "runTotal")
    val runTotal: kotlin.Int? = null

) {


}

