/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package app.marquee.api.models

import app.marquee.api.models.DeviceProfile

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param itemId 
 * @param profile 
 * @param fileId A specific version/file. Default is the best available.
 * @param audioStreamId 
 * @param subtitleStreamId -1 turns subtitles off; omit for automatic (the user's subtitle preference).
 * @param startMs Omit to resume where the user left off.
 * @param maxBitrateKbps The app's quality setting; 0/omitted = original (home) or automatic (remote).
 * @param measuredKbps Measured download speed from /playback/bandwidth-test.
 * @param preload Prepare the next item (gapless music) without ending this device's current session. It takes over when it first reports \"playing\".
 */
@Serializable

data class PlaybackRequest (

    @SerialName(value = "itemId")
    val itemId: kotlin.Long,

    @SerialName(value = "profile")
    val profile: DeviceProfile,

    /* A specific version/file. Default is the best available. */
    @SerialName(value = "fileId")
    val fileId: kotlin.Long? = null,

    @SerialName(value = "audioStreamId")
    val audioStreamId: kotlin.Long? = null,

    /* -1 turns subtitles off; omit for automatic (the user's subtitle preference). */
    @SerialName(value = "subtitleStreamId")
    val subtitleStreamId: kotlin.Long? = null,

    /* Omit to resume where the user left off. */
    @SerialName(value = "startMs")
    val startMs: kotlin.Long? = null,

    /* The app's quality setting; 0/omitted = original (home) or automatic (remote). */
    @SerialName(value = "maxBitrateKbps")
    val maxBitrateKbps: kotlin.Int? = null,

    /* Measured download speed from /playback/bandwidth-test. */
    @SerialName(value = "measuredKbps")
    val measuredKbps: kotlin.Int? = null,

    /* Prepare the next item (gapless music) without ending this device's current session. It takes over when it first reports \"playing\". */
    @SerialName(value = "preload")
    val preload: kotlin.Boolean? = null

) {


}

