/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package app.marquee.api.models

import app.marquee.api.models.Marker
import app.marquee.api.models.NetworkClass
import app.marquee.api.models.PlaybackDecision

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param id 
 * @param itemId 
 * @param url Path to play: a file (direct play), progressive audio, or an HLS master playlist.
 * @param protocol 
 * @param startMs Where to start (the resume position unless startMs was given).
 * @param durationMs 
 * @param decision 
 * @param networkClass 
 * @param markers 
 * @param fileId 
 * @param contentType The media type url is served with (e.g. video/mp4, audio/flac, application/vnd.apple.mpegurl), for players such as Chromecast that need it.
 * @param limitKbps Bitrate ceiling applied; absent = none.
 * @param limitReason 
 * @param audioStreamId 
 * @param subtitleStreamId 
 * @param subtitleUrl The selected text subtitle as WebVTT or ASS (absent when burned in or off).
 * @param subtitleFormat 
 * @param fontsUrl With ASS subtitles: JSON list of fonts embedded in the file ({name, url}[]).
 * @param trackGainDb Music: gain to apply for volume levelling (ReplayGain track gain).
 * @param albumGainDb Music: album gain, for playing whole albums.
 * @param peak Music: peak sample level (1.0 = full scale), to avoid clipping when boosting.
 */
@Serializable

data class PlaybackSession (

    @SerialName(value = "id")
    val id: kotlin.String,

    @SerialName(value = "itemId")
    val itemId: kotlin.Long,

    /* Path to play: a file (direct play), progressive audio, or an HLS master playlist. */
    @SerialName(value = "url")
    val url: kotlin.String,

    @SerialName(value = "protocol")
    val protocol: PlaybackSession.Protocol,

    /* Where to start (the resume position unless startMs was given). */
    @SerialName(value = "startMs")
    val startMs: kotlin.Long,

    @SerialName(value = "durationMs")
    val durationMs: kotlin.Long,

    @SerialName(value = "decision")
    val decision: PlaybackDecision,

    @Contextual @SerialName(value = "networkClass")
    val networkClass: NetworkClass,

    @SerialName(value = "markers")
    val markers: kotlin.collections.List<Marker>,

    @SerialName(value = "fileId")
    val fileId: kotlin.Long? = null,

    /* The media type url is served with (e.g. video/mp4, audio/flac, application/vnd.apple.mpegurl), for players such as Chromecast that need it. */
    @SerialName(value = "contentType")
    val contentType: kotlin.String? = null,

    /* Bitrate ceiling applied; absent = none. */
    @SerialName(value = "limitKbps")
    val limitKbps: kotlin.Int? = null,

    @SerialName(value = "limitReason")
    val limitReason: kotlin.String? = null,

    @SerialName(value = "audioStreamId")
    val audioStreamId: kotlin.Long? = null,

    @SerialName(value = "subtitleStreamId")
    val subtitleStreamId: kotlin.Long? = null,

    /* The selected text subtitle as WebVTT or ASS (absent when burned in or off). */
    @SerialName(value = "subtitleUrl")
    val subtitleUrl: kotlin.String? = null,

    @SerialName(value = "subtitleFormat")
    val subtitleFormat: PlaybackSession.SubtitleFormat? = null,

    /* With ASS subtitles: JSON list of fonts embedded in the file ({name, url}[]). */
    @SerialName(value = "fontsUrl")
    val fontsUrl: kotlin.String? = null,

    /* Music: gain to apply for volume levelling (ReplayGain track gain). */
    @SerialName(value = "trackGainDb")
    val trackGainDb: kotlin.Double? = null,

    /* Music: album gain, for playing whole albums. */
    @SerialName(value = "albumGainDb")
    val albumGainDb: kotlin.Double? = null,

    /* Music: peak sample level (1.0 = full scale), to avoid clipping when boosting. */
    @SerialName(value = "peak")
    val peak: kotlin.Double? = null

) {

    /**
     * 
     *
     * Values: FILE,HLS,PROGRESSIVE
     */
    @Serializable
    enum class Protocol(val value: kotlin.String) {
        @SerialName(value = "file") FILE("file"),
        @SerialName(value = "hls") HLS("hls"),
        @SerialName(value = "progressive") PROGRESSIVE("progressive");
    }
    /**
     * 
     *
     * Values: VTT,ASS
     */
    @Serializable
    enum class SubtitleFormat(val value: kotlin.String) {
        @SerialName(value = "vtt") VTT("vtt"),
        @SerialName(value = "ass") ASS("ass");
    }

}

