/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package app.marquee.api.models


import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param positionMs 
 * @param state 
 * @param error With state error: what the player reported (logged on the server for diagnosis).
 */
@Serializable

data class PlaybackProgress (

    @SerialName(value = "positionMs")
    val positionMs: kotlin.Long,

    @SerialName(value = "state")
    val state: PlaybackProgress.State,

    /* With state error: what the player reported (logged on the server for diagnosis). */
    @SerialName(value = "error")
    val error: kotlin.String? = null

) {

    /**
     * 
     *
     * Values: PLAYING,PAUSED,BUFFERING,ERROR
     */
    @Serializable
    enum class State(val value: kotlin.String) {
        @SerialName(value = "playing") PLAYING("playing"),
        @SerialName(value = "paused") PAUSED("paused"),
        @SerialName(value = "buffering") BUFFERING("buffering"),
        @SerialName(value = "error") ERROR("error");
    }

}

