/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package app.marquee.api.models


import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param id 
 * @param name 
 * @param type 
 * @param roots 
 * @param files 
 * @param matchedFiles 
 * @param libraryId Marquee library it pairs with.
 */
@Serializable

data class PlexSectionPreview (

    @SerialName(value = "id")
    val id: kotlin.Long,

    @SerialName(value = "name")
    val name: kotlin.String,

    @SerialName(value = "type")
    val type: PlexSectionPreview.Type,

    @SerialName(value = "roots")
    val roots: kotlin.collections.List<kotlin.String>,

    @SerialName(value = "files")
    val files: kotlin.Int,

    @SerialName(value = "matchedFiles")
    val matchedFiles: kotlin.Int,

    /* Marquee library it pairs with. */
    @SerialName(value = "libraryId")
    val libraryId: kotlin.Long? = null

) {

    /**
     * 
     *
     * Values: MOVIES,SHOWS,MUSIC,OTHER
     */
    @Serializable
    enum class Type(val value: kotlin.String) {
        @SerialName(value = "movies") MOVIES("movies"),
        @SerialName(value = "shows") SHOWS("shows"),
        @SerialName(value = "music") MUSIC("music"),
        @SerialName(value = "other") OTHER("other");
    }

}

