/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package app.marquee.api.models


import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param startedAt 
 * @param finishedAt 
 * @param files 
 * @param matchedFiles 
 * @param unmatchedSample 
 * @param usersCreated 
 * @param usersLinked 
 * @param matchesAgreed 
 * @param matchesApplied 
 * @param matchesKept Disagreements where Marquee's match was kept; review with Fix Match.
 * @param matchFailures 
 * @param artwork 
 * @param artworkMissing 
 * @param watchStateItems 
 * @param ratings 
 * @param historyImported 
 * @param historySkipped 
 * @param markers 
 * @param playlists 
 * @param playlistItems 
 * @param playlistItemsMissing 
 * @param warnings 
 */
@Serializable

data class PlexImportReport (

    @Contextual @SerialName(value = "startedAt")
    val startedAt: java.time.OffsetDateTime,

    @Contextual @SerialName(value = "finishedAt")
    val finishedAt: java.time.OffsetDateTime,

    @SerialName(value = "files")
    val files: kotlin.Int,

    @SerialName(value = "matchedFiles")
    val matchedFiles: kotlin.Int,

    @SerialName(value = "unmatchedSample")
    val unmatchedSample: kotlin.collections.List<kotlin.String>,

    @SerialName(value = "usersCreated")
    val usersCreated: kotlin.Int,

    @SerialName(value = "usersLinked")
    val usersLinked: kotlin.Int,

    @SerialName(value = "matchesAgreed")
    val matchesAgreed: kotlin.Int,

    @SerialName(value = "matchesApplied")
    val matchesApplied: kotlin.Int,

    /* Disagreements where Marquee's match was kept; review with Fix Match. */
    @SerialName(value = "matchesKept")
    val matchesKept: kotlin.collections.List<kotlin.String>,

    @SerialName(value = "matchFailures")
    val matchFailures: kotlin.collections.List<kotlin.String>,

    @SerialName(value = "artwork")
    val artwork: kotlin.Int,

    @SerialName(value = "artworkMissing")
    val artworkMissing: kotlin.Int,

    @SerialName(value = "watchStateItems")
    val watchStateItems: kotlin.Int,

    @SerialName(value = "ratings")
    val ratings: kotlin.Int,

    @SerialName(value = "historyImported")
    val historyImported: kotlin.Int,

    @SerialName(value = "historySkipped")
    val historySkipped: kotlin.Int,

    @SerialName(value = "markers")
    val markers: kotlin.Int,

    @SerialName(value = "playlists")
    val playlists: kotlin.Int,

    @SerialName(value = "playlistItems")
    val playlistItems: kotlin.Int,

    @SerialName(value = "playlistItemsMissing")
    val playlistItemsMissing: kotlin.Int,

    @SerialName(value = "warnings")
    val warnings: kotlin.collections.List<kotlin.String>

) {


}

