/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package app.marquee.api.models


import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param code Six characters to show on screen.
 * @param secret Kept by the device to poll for the result.
 * @param expiresAt 
 * @param pollIntervalMs 
 */
@Serializable

data class QuickConnectStart (

    /* Six characters to show on screen. */
    @SerialName(value = "code")
    val code: kotlin.String,

    /* Kept by the device to poll for the result. */
    @SerialName(value = "secret")
    val secret: kotlin.String,

    @Contextual @SerialName(value = "expiresAt")
    val expiresAt: java.time.OffsetDateTime,

    @SerialName(value = "pollIntervalMs")
    val pollIntervalMs: kotlin.Int

) {


}

