/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package app.marquee.api.models


import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param seed 
 * @param itemId With seed item: a track, album or artist.
 * @param `value` With genre: the genre; decade: e.g. 1990; mood: a word or phrase.
 * @param libraryId 
 * @param limit 
 * @param exclude Tracks already queued (to continue a station).
 */
@Serializable

data class RadioRequest (

    @SerialName(value = "seed")
    val seed: RadioRequest.Seed,

    /* With seed item: a track, album or artist. */
    @SerialName(value = "itemId")
    val itemId: kotlin.Long? = null,

    /* With genre: the genre; decade: e.g. 1990; mood: a word or phrase. */
    @SerialName(value = "value")
    val `value`: kotlin.String? = null,

    @SerialName(value = "libraryId")
    val libraryId: kotlin.Long? = null,

    @SerialName(value = "limit")
    val limit: kotlin.Int? = 50,

    /* Tracks already queued (to continue a station). */
    @SerialName(value = "exclude")
    val exclude: kotlin.collections.List<kotlin.Long>? = null

) {

    /**
     * 
     *
     * Values: ITEM,GENRE,DECADE,MOOD,FAVOURITES,LIBRARY
     */
    @Serializable
    enum class Seed(val value: kotlin.String) {
        @SerialName(value = "item") ITEM("item"),
        @SerialName(value = "genre") GENRE("genre"),
        @SerialName(value = "decade") DECADE("decade"),
        @SerialName(value = "mood") MOOD("mood"),
        @SerialName(value = "favourites") FAVOURITES("favourites"),
        @SerialName(value = "library") LIBRARY("library");
    }

}

