/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package app.marquee.api.models


import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param rating 
 * @param at When the change was made (apps send changes made offline later); an older change than the last one is ignored.
 */
@Serializable

data class RateItemRequest (

    @SerialName(value = "rating")
    val rating: kotlin.Double? = null,

    /* When the change was made (apps send changes made offline later); an older change than the last one is ignored. */
    @Contextual @SerialName(value = "at")
    val at: java.time.OffsetDateTime? = null

) {


}

