/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package app.marquee.api.models


import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param id 
 * @param title 
 * @param upcoming Airings scheduled now.
 * @param createdAt 
 * @param channelId Absent = any channel.
 * @param channelName 
 * @param userId 
 */
@Serializable

data class RecordingRule (

    @SerialName(value = "id")
    val id: kotlin.Long,

    @SerialName(value = "title")
    val title: kotlin.String,

    /* Airings scheduled now. */
    @SerialName(value = "upcoming")
    val upcoming: kotlin.Int,

    @Contextual @SerialName(value = "createdAt")
    val createdAt: java.time.OffsetDateTime,

    /* Absent = any channel. */
    @SerialName(value = "channelId")
    val channelId: kotlin.Long? = null,

    @SerialName(value = "channelName")
    val channelName: kotlin.String? = null,

    @SerialName(value = "userId")
    val userId: kotlin.Long? = null

) {


}

