/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package app.marquee.api.models

import app.marquee.api.models.RemoteCapability
import app.marquee.api.models.RemotePlayerState

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param deviceId 
 * @param name 
 * @param platform 
 * @param userId 
 * @param userName 
 * @param capabilities 
 * @param version Changes whenever the state does; pass it as ?since= to wait for the next change.
 * @param state 
 */
@Serializable

data class RemotePlayer (

    @SerialName(value = "deviceId")
    val deviceId: kotlin.Long,

    @SerialName(value = "name")
    val name: kotlin.String,

    @SerialName(value = "platform")
    val platform: kotlin.String,

    @SerialName(value = "userId")
    val userId: kotlin.Long,

    @SerialName(value = "userName")
    val userName: kotlin.String,

    @SerialName(value = "capabilities")
    val capabilities: kotlin.collections.List<@Contextual RemoteCapability>,

    /* Changes whenever the state does; pass it as ?since= to wait for the next change. */
    @SerialName(value = "version")
    val version: kotlin.Long,

    @SerialName(value = "state")
    val state: RemotePlayerState? = null

) {


}

