/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package app.marquee.api.models


import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param userId 
 * @param userName 
 * @param updatedAt 
 * @param mine 
 * @param avatarUrl 
 * @param rating Their rating, 0–10, if they rated it.
 * @param comment 
 */
@Serializable

data class Review (

    @SerialName(value = "userId")
    val userId: kotlin.Long,

    @SerialName(value = "userName")
    val userName: kotlin.String,

    @Contextual @SerialName(value = "updatedAt")
    val updatedAt: java.time.OffsetDateTime,

    @SerialName(value = "mine")
    val mine: kotlin.Boolean,

    @SerialName(value = "avatarUrl")
    val avatarUrl: kotlin.String? = null,

    /* Their rating, 0–10, if they rated it. */
    @SerialName(value = "rating")
    val rating: kotlin.Double? = null,

    @SerialName(value = "comment")
    val comment: kotlin.String? = null

) {


}

