/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package app.marquee.api.models


import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param channelId 
 * @param start The programme's start time as the guide gives it.
 * @param series Record every airing of this title.
 * @param anyChannel With series: on any channel, not only this one.
 */
@Serializable

data class ScheduleRecordingRequest (

    @SerialName(value = "channelId")
    val channelId: kotlin.Long,

    /* The programme's start time as the guide gives it. */
    @Contextual @SerialName(value = "start")
    val start: java.time.OffsetDateTime,

    /* Record every airing of this title. */
    @SerialName(value = "series")
    val series: kotlin.Boolean? = null,

    /* With series: on any channel, not only this one. */
    @SerialName(value = "anyChannel")
    val anyChannel: kotlin.Boolean? = null

) {


}

