/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package app.marquee.api.models

import app.marquee.api.models.GeneralSettings
import app.marquee.api.models.IntegrationSettingsUpdate
import app.marquee.api.models.LibraryGlobalSettings
import app.marquee.api.models.MetadataSettingsUpdate
import app.marquee.api.models.MusicSettings
import app.marquee.api.models.NetworkSettings
import app.marquee.api.models.RemoteAccessSettings
import app.marquee.api.models.SecuritySettings
import app.marquee.api.models.TaskSettings
import app.marquee.api.models.TranscoderSettings
import app.marquee.api.models.Webhook

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param security 
 * @param general 
 * @param network 
 * @param remoteAccess 
 * @param transcoder 
 * @param library 
 * @param metadata 
 * @param tasks 
 * @param music 
 * @param integrations 
 * @param webhooks Replaces the whole list when sent.
 */
@Serializable

data class ServerSettingsUpdate (

    @SerialName(value = "security")
    val security: SecuritySettings? = null,

    @SerialName(value = "general")
    val general: GeneralSettings? = null,

    @SerialName(value = "network")
    val network: NetworkSettings? = null,

    @SerialName(value = "remoteAccess")
    val remoteAccess: RemoteAccessSettings? = null,

    @SerialName(value = "transcoder")
    val transcoder: TranscoderSettings? = null,

    @SerialName(value = "library")
    val library: LibraryGlobalSettings? = null,

    @SerialName(value = "metadata")
    val metadata: MetadataSettingsUpdate? = null,

    @SerialName(value = "tasks")
    val tasks: TaskSettings? = null,

    @SerialName(value = "music")
    val music: MusicSettings? = null,

    @SerialName(value = "integrations")
    val integrations: IntegrationSettingsUpdate? = null,

    /* Replaces the whole list when sent. */
    @SerialName(value = "webhooks")
    val webhooks: kotlin.collections.List<Webhook>? = null

) {


}

