/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package app.marquee.api.models


import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param `field` energy is a percentile of the analysed library: 0 = the calmest tracks, 0.8 = more intense than 80% of them.
 * @param op 
 * @param `value` 
 */
@Serializable

data class SmartRulesConditionsInner (

    /* energy is a percentile of the analysed library: 0 = the calmest tracks, 0.8 = more intense than 80% of them. */
    @SerialName(value = "field")
    val `field`: SmartRulesConditionsInner.`Field`,

    @SerialName(value = "op")
    val op: SmartRulesConditionsInner.Op,

    @SerialName(value = "value")
    val `value`: kotlin.String

) {

    /**
     * energy is a percentile of the analysed library: 0 = the calmest tracks, 0.8 = more intense than 80% of them.
     *
     * Values: GENRE,ARTIST,ALBUM,TITLE,YEAR,RATING,PLAY_COUNT,LAST_PLAYED_DAYS,ADDED_DAYS,BPM,ENERGY,KEY,DURATION_SECONDS
     */
    @Serializable
    enum class `Field`(val value: kotlin.String) {
        @SerialName(value = "genre") GENRE("genre"),
        @SerialName(value = "artist") ARTIST("artist"),
        @SerialName(value = "album") ALBUM("album"),
        @SerialName(value = "title") TITLE("title"),
        @SerialName(value = "year") YEAR("year"),
        @SerialName(value = "rating") RATING("rating"),
        @SerialName(value = "playCount") PLAY_COUNT("playCount"),
        @SerialName(value = "lastPlayedDays") LAST_PLAYED_DAYS("lastPlayedDays"),
        @SerialName(value = "addedDays") ADDED_DAYS("addedDays"),
        @SerialName(value = "bpm") BPM("bpm"),
        @SerialName(value = "energy") ENERGY("energy"),
        @SerialName(value = "key") KEY("key"),
        @SerialName(value = "durationSeconds") DURATION_SECONDS("durationSeconds");
    }
    /**
     * 
     *
     * Values: IS,IS_NOT,CONTAINS,NOT_CONTAINS,GT,LT
     */
    @Serializable
    enum class Op(val value: kotlin.String) {
        @SerialName(value = "is") IS("is"),
        @SerialName(value = "isNot") IS_NOT("isNot"),
        @SerialName(value = "contains") CONTAINS("contains"),
        @SerialName(value = "notContains") NOT_CONTAINS("notContains"),
        @SerialName(value = "gt") GT("gt"),
        @SerialName(value = "lt") LT("lt");
    }

}

