/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package app.marquee.api.models

import app.marquee.api.models.ItemSummary

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param title 
 * @param items 
 * @param id 
 * @param description 
 */
@Serializable

data class Station (

    @SerialName(value = "title")
    val title: kotlin.String,

    @SerialName(value = "items")
    val items: kotlin.collections.List<ItemSummary>,

    @SerialName(value = "id")
    val id: kotlin.String? = null,

    @SerialName(value = "description")
    val description: kotlin.String? = null

) {


}

