/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package app.marquee.api.models

import app.marquee.api.models.StatsCount
import app.marquee.api.models.StatsDaysInner
import app.marquee.api.models.StatsMethods

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param plays 
 * @param hours 
 * @param videoHours 
 * @param musicHours 
 * @param users People who played something.
 * @param days 
 * @param movies 
 * @param shows 
 * @param artists 
 * @param albums 
 * @param tracks 
 * @param people 
 * @param platforms 
 * @param methods 
 * @param local 
 * @param remote 
 * @param since 
 */
@Serializable

data class Stats (

    @SerialName(value = "plays")
    val plays: kotlin.Int,

    @Contextual @SerialName(value = "hours")
    val hours: java.math.BigDecimal,

    @Contextual @SerialName(value = "videoHours")
    val videoHours: java.math.BigDecimal,

    @Contextual @SerialName(value = "musicHours")
    val musicHours: java.math.BigDecimal,

    /* People who played something. */
    @SerialName(value = "users")
    val users: kotlin.Int,

    @SerialName(value = "days")
    val days: kotlin.collections.List<StatsDaysInner>,

    @SerialName(value = "movies")
    val movies: kotlin.collections.List<StatsCount>,

    @SerialName(value = "shows")
    val shows: kotlin.collections.List<StatsCount>,

    @SerialName(value = "artists")
    val artists: kotlin.collections.List<StatsCount>,

    @SerialName(value = "albums")
    val albums: kotlin.collections.List<StatsCount>,

    @SerialName(value = "tracks")
    val tracks: kotlin.collections.List<StatsCount>,

    @SerialName(value = "people")
    val people: kotlin.collections.List<StatsCount>,

    @SerialName(value = "platforms")
    val platforms: kotlin.collections.List<StatsCount>,

    @SerialName(value = "methods")
    val methods: StatsMethods,

    @SerialName(value = "local")
    val local: kotlin.Int,

    @SerialName(value = "remote")
    val remote: kotlin.Int,

    @Contextual @SerialName(value = "since")
    val since: java.time.OffsetDateTime? = null

) {


}

