/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package app.marquee.api.models


import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param fileId 
 * @param language ISO 639-1 (e.g. en, pt-BR).
 * @param release 
 * @param downloads 
 * @param hearingImpaired 
 * @param aiTranslated Machine or AI translated.
 * @param hashMatch Made for this exact file.
 * @param fileName 
 * @param foreignPartsOnly 
 */
@Serializable

data class SubtitleResult (

    @SerialName(value = "fileId")
    val fileId: kotlin.Long,

    /* ISO 639-1 (e.g. en, pt-BR). */
    @SerialName(value = "language")
    val language: kotlin.String,

    @SerialName(value = "release")
    val release: kotlin.String,

    @SerialName(value = "downloads")
    val downloads: kotlin.Int,

    @SerialName(value = "hearingImpaired")
    val hearingImpaired: kotlin.Boolean,

    /* Machine or AI translated. */
    @SerialName(value = "aiTranslated")
    val aiTranslated: kotlin.Boolean,

    /* Made for this exact file. */
    @SerialName(value = "hashMatch")
    val hashMatch: kotlin.Boolean,

    @SerialName(value = "fileName")
    val fileName: kotlin.String? = null,

    @SerialName(value = "foreignPartsOnly")
    val foreignPartsOnly: kotlin.Boolean? = null

) {


}

