/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package app.marquee.api.models


import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * How text subtitles look (PLAY-20), for this person on every app and in burned-in subtitles. Styled ASS subtitles keep their own look. Absent fields use the defaults.
 *
 * @param propertySize Default medium.
 * @param color Text colour, default #FFFFFF.
 * @param background none = drop shadow only; outline = black edge (default); translucent / opaque = a box behind the text.
 * @param position raised lifts subtitles above the player's controls and lower-third captions.
 */
@Serializable

data class SubtitleStyle (

    /* Default medium. */
    @SerialName(value = "size")
    val propertySize: SubtitleStyle.PropertySize? = null,

    /* Text colour, default #FFFFFF. */
    @SerialName(value = "color")
    val color: kotlin.String? = null,

    /* none = drop shadow only; outline = black edge (default); translucent / opaque = a box behind the text. */
    @SerialName(value = "background")
    val background: SubtitleStyle.Background? = null,

    /* raised lifts subtitles above the player's controls and lower-third captions. */
    @SerialName(value = "position")
    val position: SubtitleStyle.Position? = null

) {

    /**
     * Default medium.
     *
     * Values: SMALL,MEDIUM,LARGE,HUGE
     */
    @Serializable
    enum class PropertySize(val value: kotlin.String) {
        @SerialName(value = "small") SMALL("small"),
        @SerialName(value = "medium") MEDIUM("medium"),
        @SerialName(value = "large") LARGE("large"),
        @SerialName(value = "huge") HUGE("huge");
    }
    /**
     * none = drop shadow only; outline = black edge (default); translucent / opaque = a box behind the text.
     *
     * Values: NONE,OUTLINE,TRANSLUCENT,OPAQUE
     */
    @Serializable
    enum class Background(val value: kotlin.String) {
        @SerialName(value = "none") NONE("none"),
        @SerialName(value = "outline") OUTLINE("outline"),
        @SerialName(value = "translucent") TRANSLUCENT("translucent"),
        @SerialName(value = "opaque") OPAQUE("opaque");
    }
    /**
     * raised lifts subtitles above the player's controls and lower-third captions.
     *
     * Values: BOTTOM,RAISED
     */
    @Serializable
    enum class Position(val value: kotlin.String) {
        @SerialName(value = "bottom") BOTTOM("bottom"),
        @SerialName(value = "raised") RAISED("raised");
    }

}

