/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package app.marquee.api.models


import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param positionMs 
 * @param watched Played to the end (counts a play).
 * @param playedAt 
 */
@Serializable

data class SyncProgressRequest (

    @SerialName(value = "positionMs")
    val positionMs: kotlin.Long,

    /* Played to the end (counts a play). */
    @SerialName(value = "watched")
    val watched: kotlin.Boolean? = null,

    @Contextual @SerialName(value = "playedAt")
    val playedAt: java.time.OffsetDateTime? = null

) {


}

