/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package app.marquee.api.models

import app.marquee.api.models.NetworkClass

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param serverId Stable unique server identifier.
 * @param serverName 
 * @param version 
 * @param apiVersion 
 * @param setupRequired 
 * @param networkClass 
 * @param pinSignIn The sign-in screen should offer the profile picker with PINs from this network.
 * @param lanUrl The server's home-network address (Settings → Network), so apps reached over Tailscale learn it.
 * @param remoteUrl The Tailscale address (Settings → Remote Access), so apps on the LAN learn where to go when away.
 */
@Serializable

data class SystemInfo (

    /* Stable unique server identifier. */
    @SerialName(value = "serverId")
    val serverId: kotlin.String,

    @SerialName(value = "serverName")
    val serverName: kotlin.String,

    @SerialName(value = "version")
    val version: kotlin.String,

    @SerialName(value = "apiVersion")
    val apiVersion: kotlin.String,

    @SerialName(value = "setupRequired")
    val setupRequired: kotlin.Boolean,

    @Contextual @SerialName(value = "networkClass")
    val networkClass: NetworkClass,

    /* The sign-in screen should offer the profile picker with PINs from this network. */
    @SerialName(value = "pinSignIn")
    val pinSignIn: kotlin.Boolean? = null,

    /* The server's home-network address (Settings → Network), so apps reached over Tailscale learn it. */
    @SerialName(value = "lanUrl")
    val lanUrl: kotlin.String? = null,

    /* The Tailscale address (Settings → Remote Access), so apps on the LAN learn where to go when away. */
    @SerialName(value = "remoteUrl")
    val remoteUrl: kotlin.String? = null

) {


}

