/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package app.marquee.api.models


import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param maintenanceWindowStart 
 * @param maintenanceWindowHours 
 * @param backupRetention 
 */
@Serializable

data class TaskSettings (

    @SerialName(value = "maintenanceWindowStart")
    val maintenanceWindowStart: kotlin.String? = null,

    @SerialName(value = "maintenanceWindowHours")
    val maintenanceWindowHours: kotlin.Int? = null,

    @SerialName(value = "backupRetention")
    val backupRetention: kotlin.Int? = null

) {


}

