/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package app.marquee.api.models


import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param status 
 * @param startedAt 
 * @param finishedAt 
 * @param message 
 */
@Serializable

data class TaskRun (

    @SerialName(value = "status")
    val status: TaskRun.Status,

    @Contextual @SerialName(value = "startedAt")
    val startedAt: java.time.OffsetDateTime? = null,

    @Contextual @SerialName(value = "finishedAt")
    val finishedAt: java.time.OffsetDateTime? = null,

    @SerialName(value = "message")
    val message: kotlin.String? = null

) {

    /**
     * 
     *
     * Values: RUNNING,SUCCEEDED,FAILED
     */
    @Serializable
    enum class Status(val value: kotlin.String) {
        @SerialName(value = "running") RUNNING("running"),
        @SerialName(value = "succeeded") SUCCEEDED("succeeded"),
        @SerialName(value = "failed") FAILED("failed");
    }

}

