/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package app.marquee.api.models

import app.marquee.api.models.TitleRatingsImdb
import app.marquee.api.models.TitleRatingsRottenTomatoes

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * Public ratings of a title, through Seerr. Each part is absent when unknown.
 *
 * @param rottenTomatoes 
 * @param imdb 
 */
@Serializable

data class TitleRatings (

    @SerialName(value = "rottenTomatoes")
    val rottenTomatoes: TitleRatingsRottenTomatoes? = null,

    @SerialName(value = "imdb")
    val imdb: TitleRatingsImdb? = null

) {


}

