/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package app.marquee.api.models


import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param libraryIds Libraries this user can see. Null or absent = all libraries.
 * @param maxContentRating Highest allowed rating, e.g. PG-13 or TV-14. Unrated items are hidden when set.
 * @param allowRemote May stream from outside the home network. Default true.
 * @param remoteQualityKbps Cap for remote streams. 0 = server default.
 * @param canRequest May request titles through Seerr (REQ-1). Default false; admins always may.
 * @param canRecord May schedule Live TV recordings (LIVE-5). Default false; admins always may.
 * @param seerrUserId The Seerr user requests are made as. Null = Seerr's API key owner.
 */
@Serializable

data class UserRestrictions (

    /* Libraries this user can see. Null or absent = all libraries. */
    @SerialName(value = "libraryIds")
    val libraryIds: kotlin.collections.List<kotlin.Long>? = null,

    /* Highest allowed rating, e.g. PG-13 or TV-14. Unrated items are hidden when set. */
    @SerialName(value = "maxContentRating")
    val maxContentRating: UserRestrictions.MaxContentRating? = null,

    /* May stream from outside the home network. Default true. */
    @SerialName(value = "allowRemote")
    val allowRemote: kotlin.Boolean? = null,

    /* Cap for remote streams. 0 = server default. */
    @SerialName(value = "remoteQualityKbps")
    val remoteQualityKbps: kotlin.Int? = null,

    /* May request titles through Seerr (REQ-1). Default false; admins always may. */
    @SerialName(value = "canRequest")
    val canRequest: kotlin.Boolean? = null,

    /* May schedule Live TV recordings (LIVE-5). Default false; admins always may. */
    @SerialName(value = "canRecord")
    val canRecord: kotlin.Boolean? = null,

    /* The Seerr user requests are made as. Null = Seerr's API key owner. */
    @SerialName(value = "seerrUserId")
    val seerrUserId: kotlin.Long? = null

) {

    /**
     * Highest allowed rating, e.g. PG-13 or TV-14. Unrated items are hidden when set.
     *
     * Values: G,PG,PG_13,R,NC_17,TV_Y,TV_Y7,TV_G,TV_PG,TV_14,TV_MA
     */
    @Serializable
    enum class MaxContentRating(val value: kotlin.String) {
        @SerialName(value = "G") G("G"),
        @SerialName(value = "PG") PG("PG"),
        @SerialName(value = "PG-13") PG_13("PG-13"),
        @SerialName(value = "R") R("R"),
        @SerialName(value = "NC-17") NC_17("NC-17"),
        @SerialName(value = "TV-Y") TV_Y("TV-Y"),
        @SerialName(value = "TV-Y7") TV_Y7("TV-Y7"),
        @SerialName(value = "TV-G") TV_G("TV-G"),
        @SerialName(value = "TV-PG") TV_PG("TV-PG"),
        @SerialName(value = "TV-14") TV_14("TV-14"),
        @SerialName(value = "TV-MA") TV_MA("TV-MA");
    }

}

